// -------------------------------------------------------------
//
// Module: Band_stop_filter
// Generated by MATLAB(R) 9.13 and Filter Design HDL Coder 3.1.12.
// Generated on: 2023-12-12 12:43:32
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: E:\UCL\EEE\Second_Year\0008\SX\bandstop_filter
// Name: Band_stop_filter
// TargetLanguage: Verilog
// TestBenchStimulus: step ramp chirp 

// Filter Specifications:
//
// Sample Rate          : N/A (normalized frequency)
// Response             : Bandstop
// Specification        : N,Fp1,Fp2,Ap
// Second Passband Edge : 0.2875
// First Passband Edge  : 0.28393
// Filter Order         : 2
// Passband Ripple      : 1 dB
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time IIR Filter (real)
// -------------------------------
// Filter Structure    : Direct-Form II, Second-Order Sections
// Number of Sections  : 1
// Stable              : Yes
// Linear Phase        : No
// Arithmetic          : fixed
// Numerator           : s12,10 -> [-2 2)
// Denominator         : s12,10 -> [-2 2)
// Scale Values        : s12,11 -> [-1 1)
// Input               : s12,0 -> [-2048 2048)
// Section Input       : s12,7 -> [-16 16)
// Section Output      : s12,8 -> [-8 8)
// Output              : s12,0 -> [-2048 2048)
// State               : s12,12 -> [-5.000000e-01 5.000000e-01)
// Numerator Prod      : s24,22 -> [-2 2)
// Denominator Prod    : s24,22 -> [-2 2)
// Numerator Accum     : s26,22 -> [-8 8)
// Denominator Accum   : s26,22 -> [-8 8)
// Round Mode          : convergent
// Overflow Mode       : wrap
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module Band_stop_filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [11:0] filter_in; //sfix12
  output  signed [11:0] filter_out; //sfix12

////////////////////////////////////////////////////////////////
//Module Architecture: Band_stop_filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [11:0] scaleconst1 = 12'b011111111010; //sfix12_En11
  parameter signed [11:0] coeff_b1_section1 = 12'b010000000000; //sfix12_En10
  parameter signed [11:0] coeff_b2_section1 = 12'b101100000011; //sfix12_En10
  parameter signed [11:0] coeff_b3_section1 = 12'b010000000000; //sfix12_En10
  parameter signed [11:0] coeff_a2_section1 = 12'b101100000111; //sfix12_En10
  parameter signed [11:0] coeff_a3_section1 = 12'b001111111010; //sfix12_En10
  // Signals
  reg  signed [11:0] input_register; // sfix12
  wire signed [31:0] scale1; // sfix32_En19
  wire signed [23:0] mul_temp; // sfix24_En11
  wire signed [11:0] scaletypeconvert1; // sfix12_En7
  // Section 1 Signals 
  wire signed [25:0] a1sum1; // sfix26_En22
  wire signed [25:0] a2sum1; // sfix26_En22
  wire signed [25:0] b1sum1; // sfix26_En22
  wire signed [25:0] b2sum1; // sfix26_En22
  wire signed [11:0] typeconvert1; // sfix12_En12
  reg  signed [11:0] delay_section1 [0:1] ; // sfix12_En12
  wire signed [25:0] inputconv1; // sfix26_En22
  wire signed [23:0] a2mul1; // sfix24_En22
  wire signed [23:0] a3mul1; // sfix24_En22
  wire signed [23:0] b1mul1; // sfix24_En22
  wire signed [23:0] b2mul1; // sfix24_En22
  wire signed [23:0] b3mul1; // sfix24_En22
  wire signed [25:0] sub_cast; // sfix26_En22
  wire signed [25:0] sub_cast_1; // sfix26_En22
  wire signed [26:0] sub_temp; // sfix27_En22
  wire signed [25:0] sub_cast_2; // sfix26_En22
  wire signed [25:0] sub_cast_3; // sfix26_En22
  wire signed [26:0] sub_temp_1; // sfix27_En22
  wire signed [25:0] b1multypeconvert1; // sfix26_En22
  wire signed [25:0] add_cast; // sfix26_En22
  wire signed [25:0] add_cast_1; // sfix26_En22
  wire signed [26:0] add_temp; // sfix27_En22
  wire signed [25:0] add_cast_2; // sfix26_En22
  wire signed [25:0] add_cast_3; // sfix26_En22
  wire signed [26:0] add_temp_1; // sfix27_En22
  wire signed [11:0] output_typeconvert; // sfix12
  reg  signed [11:0] output_register; // sfix12

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: input_reg_process
      if (reset == 1'b1) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  assign mul_temp = input_register * scaleconst1;
  assign scale1 = $signed({mul_temp[23:0], 8'b00000000});

  assign scaletypeconvert1 = (scale1[23:0] + {scale1[12], {11{~scale1[12]}}})>>>12;

  //   ------------------ Section 1 ------------------

  assign typeconvert1 = (a1sum1[21:0] + {a1sum1[10], {9{~a1sum1[10]}}})>>>10;

  always @ (posedge clk or posedge reset)
    begin: delay_process_section1
      if (reset == 1'b1) begin
        delay_section1[0] <= 12'b000000000000;
        delay_section1[1] <= 12'b000000000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_section1[1] <= delay_section1[0];
          delay_section1[0] <= typeconvert1;
        end
      end
    end // delay_process_section1

  assign inputconv1 = $signed({scaletypeconvert1[10:0], 15'b000000000000000});

  assign a2mul1 = delay_section1[0] * coeff_a2_section1;

  assign a3mul1 = delay_section1[1] * coeff_a3_section1;

  assign b1mul1 = $signed({typeconvert1[11:0], 10'b0000000000});

  assign b2mul1 = delay_section1[0] * coeff_b2_section1;

  assign b3mul1 = $signed({delay_section1[1][11:0], 10'b0000000000});

  assign sub_cast = inputconv1;
  assign sub_cast_1 = $signed({{2{a2mul1[23]}}, a2mul1});
  assign sub_temp = sub_cast - sub_cast_1;
  assign a2sum1 = sub_temp[25:0];

  assign sub_cast_2 = a2sum1;
  assign sub_cast_3 = $signed({{2{a3mul1[23]}}, a3mul1});
  assign sub_temp_1 = sub_cast_2 - sub_cast_3;
  assign a1sum1 = sub_temp_1[25:0];

  assign b1multypeconvert1 = $signed({{2{b1mul1[23]}}, b1mul1});

  assign add_cast = b1multypeconvert1;
  assign add_cast_1 = $signed({{2{b2mul1[23]}}, b2mul1});
  assign add_temp = add_cast + add_cast_1;
  assign b2sum1 = add_temp[25:0];

  assign add_cast_2 = b2sum1;
  assign add_cast_3 = $signed({{2{b3mul1[23]}}, b3mul1});
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign b1sum1 = add_temp_1[25:0];

  assign output_typeconvert = ({{8{b1sum1[25]}}, b1sum1[25:0]} + {b1sum1[22], {21{~b1sum1[22]}}})>>>22;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // Band_stop_filter
