// -------------------------------------------------------------
//
// Module: Fir_filterrr
// Generated by MATLAB(R) 9.13 and Filter Design HDL Coder 3.1.12.
// Generated on: 2023-12-14 14:52:15
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: E:\UCL\EEE\Second_Year\0008\SX\bandstop_filter\fir2
// Name: Fir_filterrr
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 135
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s12,11 -> [-1 1)
// Input             : s12,0 -> [-2048 2048)
// Filter Internals  : Specify Precision
//   Output          : s12,0 -> [-2048 2048)
//   Product         : s12,0 -> [-2048 2048)
//   Accumulator     : s12,0 -> [-2048 2048)
//   Round Mode      : convergent
//   Overflow Mode   : wrap
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module Fir_filterrr
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [11:0] filter_in; //sfix12
  output  signed [11:0] filter_out; //sfix12

////////////////////////////////////////////////////////////////
//Module Architecture: Fir_filterrr
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [11:0] coeff1 = 12'b111111110011; //sfix12_En11
  parameter signed [11:0] coeff2 = 12'b111111100010; //sfix12_En11
  parameter signed [11:0] coeff3 = 12'b000000001010; //sfix12_En11
  parameter signed [11:0] coeff4 = 12'b111111111101; //sfix12_En11
  parameter signed [11:0] coeff5 = 12'b000000000011; //sfix12_En11
  parameter signed [11:0] coeff6 = 12'b000000000000; //sfix12_En11
  parameter signed [11:0] coeff7 = 12'b000000000000; //sfix12_En11
  parameter signed [11:0] coeff8 = 12'b000000000000; //sfix12_En11
  parameter signed [11:0] coeff9 = 12'b000000000000; //sfix12_En11
  parameter signed [11:0] coeff10 = 12'b000000000000; //sfix12_En11
  parameter signed [11:0] coeff11 = 12'b111111111111; //sfix12_En11
  parameter signed [11:0] coeff12 = 12'b111111111110; //sfix12_En11
  parameter signed [11:0] coeff13 = 12'b111111111111; //sfix12_En11
  parameter signed [11:0] coeff14 = 12'b000000000001; //sfix12_En11
  parameter signed [11:0] coeff15 = 12'b000000000011; //sfix12_En11
  parameter signed [11:0] coeff16 = 12'b000000000100; //sfix12_En11
  parameter signed [11:0] coeff17 = 12'b000000000001; //sfix12_En11
  parameter signed [11:0] coeff18 = 12'b111111111100; //sfix12_En11
  parameter signed [11:0] coeff19 = 12'b111111111001; //sfix12_En11
  parameter signed [11:0] coeff20 = 12'b111111111011; //sfix12_En11
  parameter signed [11:0] coeff21 = 12'b000000000010; //sfix12_En11
  parameter signed [11:0] coeff22 = 12'b000000001010; //sfix12_En11
  parameter signed [11:0] coeff23 = 12'b000000001011; //sfix12_En11
  parameter signed [11:0] coeff24 = 12'b000000000011; //sfix12_En11
  parameter signed [11:0] coeff25 = 12'b111111110111; //sfix12_En11
  parameter signed [11:0] coeff26 = 12'b111111110000; //sfix12_En11
  parameter signed [11:0] coeff27 = 12'b111111110101; //sfix12_En11
  parameter signed [11:0] coeff28 = 12'b000000000100; //sfix12_En11
  parameter signed [11:0] coeff29 = 12'b000000010010; //sfix12_En11
  parameter signed [11:0] coeff30 = 12'b000000010100; //sfix12_En11
  parameter signed [11:0] coeff31 = 12'b000000000101; //sfix12_En11
  parameter signed [11:0] coeff32 = 12'b111111110000; //sfix12_En11
  parameter signed [11:0] coeff33 = 12'b111111100101; //sfix12_En11
  parameter signed [11:0] coeff34 = 12'b111111101110; //sfix12_En11
  parameter signed [11:0] coeff35 = 12'b000000000111; //sfix12_En11
  parameter signed [11:0] coeff36 = 12'b000000011101; //sfix12_En11
  parameter signed [11:0] coeff37 = 12'b000000011111; //sfix12_En11
  parameter signed [11:0] coeff38 = 12'b000000001000; //sfix12_En11
  parameter signed [11:0] coeff39 = 12'b111111101001; //sfix12_En11
  parameter signed [11:0] coeff40 = 12'b111111011001; //sfix12_En11
  parameter signed [11:0] coeff41 = 12'b111111100110; //sfix12_En11
  parameter signed [11:0] coeff42 = 12'b000000001010; //sfix12_En11
  parameter signed [11:0] coeff43 = 12'b000000101000; //sfix12_En11
  parameter signed [11:0] coeff44 = 12'b000000101010; //sfix12_En11
  parameter signed [11:0] coeff45 = 12'b000000001011; //sfix12_En11
  parameter signed [11:0] coeff46 = 12'b111111100001; //sfix12_En11
  parameter signed [11:0] coeff47 = 12'b111111001101; //sfix12_En11
  parameter signed [11:0] coeff48 = 12'b111111011111; //sfix12_En11
  parameter signed [11:0] coeff49 = 12'b000000001100; //sfix12_En11
  parameter signed [11:0] coeff50 = 12'b000000110010; //sfix12_En11
  parameter signed [11:0] coeff51 = 12'b000000110100; //sfix12_En11
  parameter signed [11:0] coeff52 = 12'b000000001101; //sfix12_En11
  parameter signed [11:0] coeff53 = 12'b111111011011; //sfix12_En11
  parameter signed [11:0] coeff54 = 12'b111111000011; //sfix12_En11
  parameter signed [11:0] coeff55 = 12'b111111011001; //sfix12_En11
  parameter signed [11:0] coeff56 = 12'b000000001110; //sfix12_En11
  parameter signed [11:0] coeff57 = 12'b000000111010; //sfix12_En11
  parameter signed [11:0] coeff58 = 12'b000000111011; //sfix12_En11
  parameter signed [11:0] coeff59 = 12'b000000001111; //sfix12_En11
  parameter signed [11:0] coeff60 = 12'b111111010110; //sfix12_En11
  parameter signed [11:0] coeff61 = 12'b111110111100; //sfix12_En11
  parameter signed [11:0] coeff62 = 12'b111111010101; //sfix12_En11
  parameter signed [11:0] coeff63 = 12'b000000001111; //sfix12_En11
  parameter signed [11:0] coeff64 = 12'b000000111111; //sfix12_En11
  parameter signed [11:0] coeff65 = 12'b000000111111; //sfix12_En11
  parameter signed [11:0] coeff66 = 12'b000000010000; //sfix12_En11
  parameter signed [11:0] coeff67 = 12'b111111010100; //sfix12_En11
  parameter signed [11:0] coeff68 = 12'b011110111010; //sfix12_En11
  parameter signed [11:0] coeff69 = 12'b111111010100; //sfix12_En11
  parameter signed [11:0] coeff70 = 12'b000000010000; //sfix12_En11
  parameter signed [11:0] coeff71 = 12'b000000111111; //sfix12_En11
  parameter signed [11:0] coeff72 = 12'b000000111111; //sfix12_En11
  parameter signed [11:0] coeff73 = 12'b000000001111; //sfix12_En11
  parameter signed [11:0] coeff74 = 12'b111111010101; //sfix12_En11
  parameter signed [11:0] coeff75 = 12'b111110111100; //sfix12_En11
  parameter signed [11:0] coeff76 = 12'b111111010110; //sfix12_En11
  parameter signed [11:0] coeff77 = 12'b000000001111; //sfix12_En11
  parameter signed [11:0] coeff78 = 12'b000000111011; //sfix12_En11
  parameter signed [11:0] coeff79 = 12'b000000111010; //sfix12_En11
  parameter signed [11:0] coeff80 = 12'b000000001110; //sfix12_En11
  parameter signed [11:0] coeff81 = 12'b111111011001; //sfix12_En11
  parameter signed [11:0] coeff82 = 12'b111111000011; //sfix12_En11
  parameter signed [11:0] coeff83 = 12'b111111011011; //sfix12_En11
  parameter signed [11:0] coeff84 = 12'b000000001101; //sfix12_En11
  parameter signed [11:0] coeff85 = 12'b000000110100; //sfix12_En11
  parameter signed [11:0] coeff86 = 12'b000000110010; //sfix12_En11
  parameter signed [11:0] coeff87 = 12'b000000001100; //sfix12_En11
  parameter signed [11:0] coeff88 = 12'b111111011111; //sfix12_En11
  parameter signed [11:0] coeff89 = 12'b111111001101; //sfix12_En11
  parameter signed [11:0] coeff90 = 12'b111111100001; //sfix12_En11
  parameter signed [11:0] coeff91 = 12'b000000001011; //sfix12_En11
  parameter signed [11:0] coeff92 = 12'b000000101010; //sfix12_En11
  parameter signed [11:0] coeff93 = 12'b000000101000; //sfix12_En11
  parameter signed [11:0] coeff94 = 12'b000000001010; //sfix12_En11
  parameter signed [11:0] coeff95 = 12'b111111100110; //sfix12_En11
  parameter signed [11:0] coeff96 = 12'b111111011001; //sfix12_En11
  parameter signed [11:0] coeff97 = 12'b111111101001; //sfix12_En11
  parameter signed [11:0] coeff98 = 12'b000000001000; //sfix12_En11
  parameter signed [11:0] coeff99 = 12'b000000011111; //sfix12_En11
  parameter signed [11:0] coeff100 = 12'b000000011101; //sfix12_En11
  parameter signed [11:0] coeff101 = 12'b000000000111; //sfix12_En11
  parameter signed [11:0] coeff102 = 12'b111111101110; //sfix12_En11
  parameter signed [11:0] coeff103 = 12'b111111100101; //sfix12_En11
  parameter signed [11:0] coeff104 = 12'b111111110000; //sfix12_En11
  parameter signed [11:0] coeff105 = 12'b000000000101; //sfix12_En11
  parameter signed [11:0] coeff106 = 12'b000000010100; //sfix12_En11
  parameter signed [11:0] coeff107 = 12'b000000010010; //sfix12_En11
  parameter signed [11:0] coeff108 = 12'b000000000100; //sfix12_En11
  parameter signed [11:0] coeff109 = 12'b111111110101; //sfix12_En11
  parameter signed [11:0] coeff110 = 12'b111111110000; //sfix12_En11
  parameter signed [11:0] coeff111 = 12'b111111110111; //sfix12_En11
  parameter signed [11:0] coeff112 = 12'b000000000011; //sfix12_En11
  parameter signed [11:0] coeff113 = 12'b000000001011; //sfix12_En11
  parameter signed [11:0] coeff114 = 12'b000000001010; //sfix12_En11
  parameter signed [11:0] coeff115 = 12'b000000000010; //sfix12_En11
  parameter signed [11:0] coeff116 = 12'b111111111011; //sfix12_En11
  parameter signed [11:0] coeff117 = 12'b111111111001; //sfix12_En11
  parameter signed [11:0] coeff118 = 12'b111111111100; //sfix12_En11
  parameter signed [11:0] coeff119 = 12'b000000000001; //sfix12_En11
  parameter signed [11:0] coeff120 = 12'b000000000100; //sfix12_En11
  parameter signed [11:0] coeff121 = 12'b000000000011; //sfix12_En11
  parameter signed [11:0] coeff122 = 12'b000000000001; //sfix12_En11
  parameter signed [11:0] coeff123 = 12'b111111111111; //sfix12_En11
  parameter signed [11:0] coeff124 = 12'b111111111110; //sfix12_En11
  parameter signed [11:0] coeff125 = 12'b111111111111; //sfix12_En11
  parameter signed [11:0] coeff126 = 12'b000000000000; //sfix12_En11
  parameter signed [11:0] coeff127 = 12'b000000000000; //sfix12_En11
  parameter signed [11:0] coeff128 = 12'b000000000000; //sfix12_En11
  parameter signed [11:0] coeff129 = 12'b000000000000; //sfix12_En11
  parameter signed [11:0] coeff130 = 12'b000000000000; //sfix12_En11
  parameter signed [11:0] coeff131 = 12'b000000000011; //sfix12_En11
  parameter signed [11:0] coeff132 = 12'b111111111101; //sfix12_En11
  parameter signed [11:0] coeff133 = 12'b000000001010; //sfix12_En11
  parameter signed [11:0] coeff134 = 12'b111111100010; //sfix12_En11
  parameter signed [11:0] coeff135 = 12'b111111110011; //sfix12_En11

  // Signals
  reg  signed [11:0] delay_pipeline [0:134] ; // sfix12
  wire signed [11:0] product135; // sfix12
  wire signed [23:0] mul_temp; // sfix24_En11
  wire signed [11:0] product134; // sfix12
  wire signed [23:0] mul_temp_1; // sfix24_En11
  wire signed [11:0] product133; // sfix12
  wire signed [23:0] mul_temp_2; // sfix24_En11
  wire signed [11:0] product132; // sfix12
  wire signed [23:0] mul_temp_3; // sfix24_En11
  wire signed [11:0] product131; // sfix12
  wire signed [23:0] mul_temp_4; // sfix24_En11
  wire signed [11:0] product125; // sfix12
  wire signed [12:0] mulpwr2_temp; // sfix13
  wire signed [11:0] product124; // sfix12
  wire signed [12:0] mulpwr2_temp_1; // sfix13
  wire signed [11:0] product123; // sfix12
  wire signed [12:0] mulpwr2_temp_2; // sfix13
  wire signed [11:0] product122; // sfix12
  wire signed [11:0] product121; // sfix12
  wire signed [23:0] mul_temp_5; // sfix24_En11
  wire signed [11:0] product120; // sfix12
  wire signed [11:0] product119; // sfix12
  wire signed [11:0] product118; // sfix12
  wire signed [12:0] mulpwr2_temp_3; // sfix13
  wire signed [11:0] product117; // sfix12
  wire signed [23:0] mul_temp_6; // sfix24_En11
  wire signed [11:0] product116; // sfix12
  wire signed [23:0] mul_temp_7; // sfix24_En11
  wire signed [11:0] product115; // sfix12
  wire signed [11:0] product114; // sfix12
  wire signed [23:0] mul_temp_8; // sfix24_En11
  wire signed [11:0] product113; // sfix12
  wire signed [23:0] mul_temp_9; // sfix24_En11
  wire signed [11:0] product112; // sfix12
  wire signed [23:0] mul_temp_10; // sfix24_En11
  wire signed [11:0] product111; // sfix12
  wire signed [23:0] mul_temp_11; // sfix24_En11
  wire signed [11:0] product110; // sfix12
  wire signed [12:0] mulpwr2_temp_4; // sfix13
  wire signed [11:0] product109; // sfix12
  wire signed [23:0] mul_temp_12; // sfix24_En11
  wire signed [11:0] product108; // sfix12
  wire signed [11:0] product107; // sfix12
  wire signed [23:0] mul_temp_13; // sfix24_En11
  wire signed [11:0] product106; // sfix12
  wire signed [23:0] mul_temp_14; // sfix24_En11
  wire signed [11:0] product105; // sfix12
  wire signed [23:0] mul_temp_15; // sfix24_En11
  wire signed [11:0] product104; // sfix12
  wire signed [12:0] mulpwr2_temp_5; // sfix13
  wire signed [11:0] product103; // sfix12
  wire signed [23:0] mul_temp_16; // sfix24_En11
  wire signed [11:0] product102; // sfix12
  wire signed [23:0] mul_temp_17; // sfix24_En11
  wire signed [11:0] product101; // sfix12
  wire signed [23:0] mul_temp_18; // sfix24_En11
  wire signed [11:0] product100; // sfix12
  wire signed [23:0] mul_temp_19; // sfix24_En11
  wire signed [11:0] product99; // sfix12
  wire signed [23:0] mul_temp_20; // sfix24_En11
  wire signed [11:0] product98; // sfix12
  wire signed [11:0] product97; // sfix12
  wire signed [23:0] mul_temp_21; // sfix24_En11
  wire signed [11:0] product96; // sfix12
  wire signed [23:0] mul_temp_22; // sfix24_En11
  wire signed [11:0] product95; // sfix12
  wire signed [23:0] mul_temp_23; // sfix24_En11
  wire signed [11:0] product94; // sfix12
  wire signed [23:0] mul_temp_24; // sfix24_En11
  wire signed [11:0] product93; // sfix12
  wire signed [23:0] mul_temp_25; // sfix24_En11
  wire signed [11:0] product92; // sfix12
  wire signed [23:0] mul_temp_26; // sfix24_En11
  wire signed [11:0] product91; // sfix12
  wire signed [23:0] mul_temp_27; // sfix24_En11
  wire signed [11:0] product90; // sfix12
  wire signed [23:0] mul_temp_28; // sfix24_En11
  wire signed [11:0] product89; // sfix12
  wire signed [23:0] mul_temp_29; // sfix24_En11
  wire signed [11:0] product88; // sfix12
  wire signed [23:0] mul_temp_30; // sfix24_En11
  wire signed [11:0] product87; // sfix12
  wire signed [23:0] mul_temp_31; // sfix24_En11
  wire signed [11:0] product86; // sfix12
  wire signed [23:0] mul_temp_32; // sfix24_En11
  wire signed [11:0] product85; // sfix12
  wire signed [23:0] mul_temp_33; // sfix24_En11
  wire signed [11:0] product84; // sfix12
  wire signed [23:0] mul_temp_34; // sfix24_En11
  wire signed [11:0] product83; // sfix12
  wire signed [23:0] mul_temp_35; // sfix24_En11
  wire signed [11:0] product82; // sfix12
  wire signed [23:0] mul_temp_36; // sfix24_En11
  wire signed [11:0] product81; // sfix12
  wire signed [23:0] mul_temp_37; // sfix24_En11
  wire signed [11:0] product80; // sfix12
  wire signed [23:0] mul_temp_38; // sfix24_En11
  wire signed [11:0] product79; // sfix12
  wire signed [23:0] mul_temp_39; // sfix24_En11
  wire signed [11:0] product78; // sfix12
  wire signed [23:0] mul_temp_40; // sfix24_En11
  wire signed [11:0] product77; // sfix12
  wire signed [23:0] mul_temp_41; // sfix24_En11
  wire signed [11:0] product76; // sfix12
  wire signed [23:0] mul_temp_42; // sfix24_En11
  wire signed [11:0] product75; // sfix12
  wire signed [23:0] mul_temp_43; // sfix24_En11
  wire signed [11:0] product74; // sfix12
  wire signed [23:0] mul_temp_44; // sfix24_En11
  wire signed [11:0] product73; // sfix12
  wire signed [23:0] mul_temp_45; // sfix24_En11
  wire signed [11:0] product72; // sfix12
  wire signed [23:0] mul_temp_46; // sfix24_En11
  wire signed [11:0] product71; // sfix12
  wire signed [23:0] mul_temp_47; // sfix24_En11
  wire signed [11:0] product70; // sfix12
  wire signed [11:0] product69; // sfix12
  wire signed [23:0] mul_temp_48; // sfix24_En11
  wire signed [11:0] product68; // sfix12
  wire signed [23:0] mul_temp_49; // sfix24_En11
  wire signed [11:0] product67; // sfix12
  wire signed [23:0] mul_temp_50; // sfix24_En11
  wire signed [11:0] product66; // sfix12
  wire signed [11:0] product65; // sfix12
  wire signed [23:0] mul_temp_51; // sfix24_En11
  wire signed [11:0] product64; // sfix12
  wire signed [23:0] mul_temp_52; // sfix24_En11
  wire signed [11:0] product63; // sfix12
  wire signed [23:0] mul_temp_53; // sfix24_En11
  wire signed [11:0] product62; // sfix12
  wire signed [23:0] mul_temp_54; // sfix24_En11
  wire signed [11:0] product61; // sfix12
  wire signed [23:0] mul_temp_55; // sfix24_En11
  wire signed [11:0] product60; // sfix12
  wire signed [23:0] mul_temp_56; // sfix24_En11
  wire signed [11:0] product59; // sfix12
  wire signed [23:0] mul_temp_57; // sfix24_En11
  wire signed [11:0] product58; // sfix12
  wire signed [23:0] mul_temp_58; // sfix24_En11
  wire signed [11:0] product57; // sfix12
  wire signed [23:0] mul_temp_59; // sfix24_En11
  wire signed [11:0] product56; // sfix12
  wire signed [23:0] mul_temp_60; // sfix24_En11
  wire signed [11:0] product55; // sfix12
  wire signed [23:0] mul_temp_61; // sfix24_En11
  wire signed [11:0] product54; // sfix12
  wire signed [23:0] mul_temp_62; // sfix24_En11
  wire signed [11:0] product53; // sfix12
  wire signed [23:0] mul_temp_63; // sfix24_En11
  wire signed [11:0] product52; // sfix12
  wire signed [23:0] mul_temp_64; // sfix24_En11
  wire signed [11:0] product51; // sfix12
  wire signed [23:0] mul_temp_65; // sfix24_En11
  wire signed [11:0] product50; // sfix12
  wire signed [23:0] mul_temp_66; // sfix24_En11
  wire signed [11:0] product49; // sfix12
  wire signed [23:0] mul_temp_67; // sfix24_En11
  wire signed [11:0] product48; // sfix12
  wire signed [23:0] mul_temp_68; // sfix24_En11
  wire signed [11:0] product47; // sfix12
  wire signed [23:0] mul_temp_69; // sfix24_En11
  wire signed [11:0] product46; // sfix12
  wire signed [23:0] mul_temp_70; // sfix24_En11
  wire signed [11:0] product45; // sfix12
  wire signed [23:0] mul_temp_71; // sfix24_En11
  wire signed [11:0] product44; // sfix12
  wire signed [23:0] mul_temp_72; // sfix24_En11
  wire signed [11:0] product43; // sfix12
  wire signed [23:0] mul_temp_73; // sfix24_En11
  wire signed [11:0] product42; // sfix12
  wire signed [23:0] mul_temp_74; // sfix24_En11
  wire signed [11:0] product41; // sfix12
  wire signed [23:0] mul_temp_75; // sfix24_En11
  wire signed [11:0] product40; // sfix12
  wire signed [23:0] mul_temp_76; // sfix24_En11
  wire signed [11:0] product39; // sfix12
  wire signed [23:0] mul_temp_77; // sfix24_En11
  wire signed [11:0] product38; // sfix12
  wire signed [11:0] product37; // sfix12
  wire signed [23:0] mul_temp_78; // sfix24_En11
  wire signed [11:0] product36; // sfix12
  wire signed [23:0] mul_temp_79; // sfix24_En11
  wire signed [11:0] product35; // sfix12
  wire signed [23:0] mul_temp_80; // sfix24_En11
  wire signed [11:0] product34; // sfix12
  wire signed [23:0] mul_temp_81; // sfix24_En11
  wire signed [11:0] product33; // sfix12
  wire signed [23:0] mul_temp_82; // sfix24_En11
  wire signed [11:0] product32; // sfix12
  wire signed [12:0] mulpwr2_temp_6; // sfix13
  wire signed [11:0] product31; // sfix12
  wire signed [23:0] mul_temp_83; // sfix24_En11
  wire signed [11:0] product30; // sfix12
  wire signed [23:0] mul_temp_84; // sfix24_En11
  wire signed [11:0] product29; // sfix12
  wire signed [23:0] mul_temp_85; // sfix24_En11
  wire signed [11:0] product28; // sfix12
  wire signed [11:0] product27; // sfix12
  wire signed [23:0] mul_temp_86; // sfix24_En11
  wire signed [11:0] product26; // sfix12
  wire signed [12:0] mulpwr2_temp_7; // sfix13
  wire signed [11:0] product25; // sfix12
  wire signed [23:0] mul_temp_87; // sfix24_En11
  wire signed [11:0] product24; // sfix12
  wire signed [23:0] mul_temp_88; // sfix24_En11
  wire signed [11:0] product23; // sfix12
  wire signed [23:0] mul_temp_89; // sfix24_En11
  wire signed [11:0] product22; // sfix12
  wire signed [23:0] mul_temp_90; // sfix24_En11
  wire signed [11:0] product21; // sfix12
  wire signed [11:0] product20; // sfix12
  wire signed [23:0] mul_temp_91; // sfix24_En11
  wire signed [11:0] product19; // sfix12
  wire signed [23:0] mul_temp_92; // sfix24_En11
  wire signed [11:0] product18; // sfix12
  wire signed [12:0] mulpwr2_temp_8; // sfix13
  wire signed [11:0] product17; // sfix12
  wire signed [11:0] product16; // sfix12
  wire signed [11:0] product15; // sfix12
  wire signed [23:0] mul_temp_93; // sfix24_En11
  wire signed [11:0] product14; // sfix12
  wire signed [11:0] product13; // sfix12
  wire signed [12:0] mulpwr2_temp_9; // sfix13
  wire signed [11:0] product12; // sfix12
  wire signed [12:0] mulpwr2_temp_10; // sfix13
  wire signed [11:0] product11; // sfix12
  wire signed [12:0] mulpwr2_temp_11; // sfix13
  wire signed [11:0] product5; // sfix12
  wire signed [23:0] mul_temp_94; // sfix24_En11
  wire signed [11:0] product4; // sfix12
  wire signed [23:0] mul_temp_95; // sfix24_En11
  wire signed [11:0] product3; // sfix12
  wire signed [23:0] mul_temp_96; // sfix24_En11
  wire signed [11:0] product2; // sfix12
  wire signed [23:0] mul_temp_97; // sfix24_En11
  wire signed [11:0] product1_cast; // sfix12
  wire signed [11:0] product1; // sfix12
  wire signed [23:0] mul_temp_98; // sfix24_En11
  wire signed [11:0] sum1; // sfix12
  wire signed [11:0] add_signext; // sfix12
  wire signed [11:0] add_signext_1; // sfix12
  wire signed [12:0] add_temp; // sfix13
  wire signed [11:0] sum2; // sfix12
  wire signed [11:0] add_signext_2; // sfix12
  wire signed [11:0] add_signext_3; // sfix12
  wire signed [12:0] add_temp_1; // sfix13
  wire signed [11:0] sum3; // sfix12
  wire signed [11:0] add_signext_4; // sfix12
  wire signed [11:0] add_signext_5; // sfix12
  wire signed [12:0] add_temp_2; // sfix13
  wire signed [11:0] sum4; // sfix12
  wire signed [11:0] add_signext_6; // sfix12
  wire signed [11:0] add_signext_7; // sfix12
  wire signed [12:0] add_temp_3; // sfix13
  wire signed [11:0] sum5; // sfix12
  wire signed [11:0] add_signext_8; // sfix12
  wire signed [11:0] add_signext_9; // sfix12
  wire signed [12:0] add_temp_4; // sfix13
  wire signed [11:0] sum6; // sfix12
  wire signed [11:0] add_signext_10; // sfix12
  wire signed [11:0] add_signext_11; // sfix12
  wire signed [12:0] add_temp_5; // sfix13
  wire signed [11:0] sum7; // sfix12
  wire signed [11:0] add_signext_12; // sfix12
  wire signed [11:0] add_signext_13; // sfix12
  wire signed [12:0] add_temp_6; // sfix13
  wire signed [11:0] sum8; // sfix12
  wire signed [11:0] add_signext_14; // sfix12
  wire signed [11:0] add_signext_15; // sfix12
  wire signed [12:0] add_temp_7; // sfix13
  wire signed [11:0] sum9; // sfix12
  wire signed [11:0] add_signext_16; // sfix12
  wire signed [11:0] add_signext_17; // sfix12
  wire signed [12:0] add_temp_8; // sfix13
  wire signed [11:0] sum10; // sfix12
  wire signed [11:0] add_signext_18; // sfix12
  wire signed [11:0] add_signext_19; // sfix12
  wire signed [12:0] add_temp_9; // sfix13
  wire signed [11:0] sum11; // sfix12
  wire signed [11:0] add_signext_20; // sfix12
  wire signed [11:0] add_signext_21; // sfix12
  wire signed [12:0] add_temp_10; // sfix13
  wire signed [11:0] sum12; // sfix12
  wire signed [11:0] add_signext_22; // sfix12
  wire signed [11:0] add_signext_23; // sfix12
  wire signed [12:0] add_temp_11; // sfix13
  wire signed [11:0] sum13; // sfix12
  wire signed [11:0] add_signext_24; // sfix12
  wire signed [11:0] add_signext_25; // sfix12
  wire signed [12:0] add_temp_12; // sfix13
  wire signed [11:0] sum14; // sfix12
  wire signed [11:0] add_signext_26; // sfix12
  wire signed [11:0] add_signext_27; // sfix12
  wire signed [12:0] add_temp_13; // sfix13
  wire signed [11:0] sum15; // sfix12
  wire signed [11:0] add_signext_28; // sfix12
  wire signed [11:0] add_signext_29; // sfix12
  wire signed [12:0] add_temp_14; // sfix13
  wire signed [11:0] sum16; // sfix12
  wire signed [11:0] add_signext_30; // sfix12
  wire signed [11:0] add_signext_31; // sfix12
  wire signed [12:0] add_temp_15; // sfix13
  wire signed [11:0] sum17; // sfix12
  wire signed [11:0] add_signext_32; // sfix12
  wire signed [11:0] add_signext_33; // sfix12
  wire signed [12:0] add_temp_16; // sfix13
  wire signed [11:0] sum18; // sfix12
  wire signed [11:0] add_signext_34; // sfix12
  wire signed [11:0] add_signext_35; // sfix12
  wire signed [12:0] add_temp_17; // sfix13
  wire signed [11:0] sum19; // sfix12
  wire signed [11:0] add_signext_36; // sfix12
  wire signed [11:0] add_signext_37; // sfix12
  wire signed [12:0] add_temp_18; // sfix13
  wire signed [11:0] sum20; // sfix12
  wire signed [11:0] add_signext_38; // sfix12
  wire signed [11:0] add_signext_39; // sfix12
  wire signed [12:0] add_temp_19; // sfix13
  wire signed [11:0] sum21; // sfix12
  wire signed [11:0] add_signext_40; // sfix12
  wire signed [11:0] add_signext_41; // sfix12
  wire signed [12:0] add_temp_20; // sfix13
  wire signed [11:0] sum22; // sfix12
  wire signed [11:0] add_signext_42; // sfix12
  wire signed [11:0] add_signext_43; // sfix12
  wire signed [12:0] add_temp_21; // sfix13
  wire signed [11:0] sum23; // sfix12
  wire signed [11:0] add_signext_44; // sfix12
  wire signed [11:0] add_signext_45; // sfix12
  wire signed [12:0] add_temp_22; // sfix13
  wire signed [11:0] sum24; // sfix12
  wire signed [11:0] add_signext_46; // sfix12
  wire signed [11:0] add_signext_47; // sfix12
  wire signed [12:0] add_temp_23; // sfix13
  wire signed [11:0] sum25; // sfix12
  wire signed [11:0] add_signext_48; // sfix12
  wire signed [11:0] add_signext_49; // sfix12
  wire signed [12:0] add_temp_24; // sfix13
  wire signed [11:0] sum26; // sfix12
  wire signed [11:0] add_signext_50; // sfix12
  wire signed [11:0] add_signext_51; // sfix12
  wire signed [12:0] add_temp_25; // sfix13
  wire signed [11:0] sum27; // sfix12
  wire signed [11:0] add_signext_52; // sfix12
  wire signed [11:0] add_signext_53; // sfix12
  wire signed [12:0] add_temp_26; // sfix13
  wire signed [11:0] sum28; // sfix12
  wire signed [11:0] add_signext_54; // sfix12
  wire signed [11:0] add_signext_55; // sfix12
  wire signed [12:0] add_temp_27; // sfix13
  wire signed [11:0] sum29; // sfix12
  wire signed [11:0] add_signext_56; // sfix12
  wire signed [11:0] add_signext_57; // sfix12
  wire signed [12:0] add_temp_28; // sfix13
  wire signed [11:0] sum30; // sfix12
  wire signed [11:0] add_signext_58; // sfix12
  wire signed [11:0] add_signext_59; // sfix12
  wire signed [12:0] add_temp_29; // sfix13
  wire signed [11:0] sum31; // sfix12
  wire signed [11:0] add_signext_60; // sfix12
  wire signed [11:0] add_signext_61; // sfix12
  wire signed [12:0] add_temp_30; // sfix13
  wire signed [11:0] sum32; // sfix12
  wire signed [11:0] add_signext_62; // sfix12
  wire signed [11:0] add_signext_63; // sfix12
  wire signed [12:0] add_temp_31; // sfix13
  wire signed [11:0] sum33; // sfix12
  wire signed [11:0] add_signext_64; // sfix12
  wire signed [11:0] add_signext_65; // sfix12
  wire signed [12:0] add_temp_32; // sfix13
  wire signed [11:0] sum34; // sfix12
  wire signed [11:0] add_signext_66; // sfix12
  wire signed [11:0] add_signext_67; // sfix12
  wire signed [12:0] add_temp_33; // sfix13
  wire signed [11:0] sum35; // sfix12
  wire signed [11:0] add_signext_68; // sfix12
  wire signed [11:0] add_signext_69; // sfix12
  wire signed [12:0] add_temp_34; // sfix13
  wire signed [11:0] sum36; // sfix12
  wire signed [11:0] add_signext_70; // sfix12
  wire signed [11:0] add_signext_71; // sfix12
  wire signed [12:0] add_temp_35; // sfix13
  wire signed [11:0] sum37; // sfix12
  wire signed [11:0] add_signext_72; // sfix12
  wire signed [11:0] add_signext_73; // sfix12
  wire signed [12:0] add_temp_36; // sfix13
  wire signed [11:0] sum38; // sfix12
  wire signed [11:0] add_signext_74; // sfix12
  wire signed [11:0] add_signext_75; // sfix12
  wire signed [12:0] add_temp_37; // sfix13
  wire signed [11:0] sum39; // sfix12
  wire signed [11:0] add_signext_76; // sfix12
  wire signed [11:0] add_signext_77; // sfix12
  wire signed [12:0] add_temp_38; // sfix13
  wire signed [11:0] sum40; // sfix12
  wire signed [11:0] add_signext_78; // sfix12
  wire signed [11:0] add_signext_79; // sfix12
  wire signed [12:0] add_temp_39; // sfix13
  wire signed [11:0] sum41; // sfix12
  wire signed [11:0] add_signext_80; // sfix12
  wire signed [11:0] add_signext_81; // sfix12
  wire signed [12:0] add_temp_40; // sfix13
  wire signed [11:0] sum42; // sfix12
  wire signed [11:0] add_signext_82; // sfix12
  wire signed [11:0] add_signext_83; // sfix12
  wire signed [12:0] add_temp_41; // sfix13
  wire signed [11:0] sum43; // sfix12
  wire signed [11:0] add_signext_84; // sfix12
  wire signed [11:0] add_signext_85; // sfix12
  wire signed [12:0] add_temp_42; // sfix13
  wire signed [11:0] sum44; // sfix12
  wire signed [11:0] add_signext_86; // sfix12
  wire signed [11:0] add_signext_87; // sfix12
  wire signed [12:0] add_temp_43; // sfix13
  wire signed [11:0] sum45; // sfix12
  wire signed [11:0] add_signext_88; // sfix12
  wire signed [11:0] add_signext_89; // sfix12
  wire signed [12:0] add_temp_44; // sfix13
  wire signed [11:0] sum46; // sfix12
  wire signed [11:0] add_signext_90; // sfix12
  wire signed [11:0] add_signext_91; // sfix12
  wire signed [12:0] add_temp_45; // sfix13
  wire signed [11:0] sum47; // sfix12
  wire signed [11:0] add_signext_92; // sfix12
  wire signed [11:0] add_signext_93; // sfix12
  wire signed [12:0] add_temp_46; // sfix13
  wire signed [11:0] sum48; // sfix12
  wire signed [11:0] add_signext_94; // sfix12
  wire signed [11:0] add_signext_95; // sfix12
  wire signed [12:0] add_temp_47; // sfix13
  wire signed [11:0] sum49; // sfix12
  wire signed [11:0] add_signext_96; // sfix12
  wire signed [11:0] add_signext_97; // sfix12
  wire signed [12:0] add_temp_48; // sfix13
  wire signed [11:0] sum50; // sfix12
  wire signed [11:0] add_signext_98; // sfix12
  wire signed [11:0] add_signext_99; // sfix12
  wire signed [12:0] add_temp_49; // sfix13
  wire signed [11:0] sum51; // sfix12
  wire signed [11:0] add_signext_100; // sfix12
  wire signed [11:0] add_signext_101; // sfix12
  wire signed [12:0] add_temp_50; // sfix13
  wire signed [11:0] sum52; // sfix12
  wire signed [11:0] add_signext_102; // sfix12
  wire signed [11:0] add_signext_103; // sfix12
  wire signed [12:0] add_temp_51; // sfix13
  wire signed [11:0] sum53; // sfix12
  wire signed [11:0] add_signext_104; // sfix12
  wire signed [11:0] add_signext_105; // sfix12
  wire signed [12:0] add_temp_52; // sfix13
  wire signed [11:0] sum54; // sfix12
  wire signed [11:0] add_signext_106; // sfix12
  wire signed [11:0] add_signext_107; // sfix12
  wire signed [12:0] add_temp_53; // sfix13
  wire signed [11:0] sum55; // sfix12
  wire signed [11:0] add_signext_108; // sfix12
  wire signed [11:0] add_signext_109; // sfix12
  wire signed [12:0] add_temp_54; // sfix13
  wire signed [11:0] sum56; // sfix12
  wire signed [11:0] add_signext_110; // sfix12
  wire signed [11:0] add_signext_111; // sfix12
  wire signed [12:0] add_temp_55; // sfix13
  wire signed [11:0] sum57; // sfix12
  wire signed [11:0] add_signext_112; // sfix12
  wire signed [11:0] add_signext_113; // sfix12
  wire signed [12:0] add_temp_56; // sfix13
  wire signed [11:0] sum58; // sfix12
  wire signed [11:0] add_signext_114; // sfix12
  wire signed [11:0] add_signext_115; // sfix12
  wire signed [12:0] add_temp_57; // sfix13
  wire signed [11:0] sum59; // sfix12
  wire signed [11:0] add_signext_116; // sfix12
  wire signed [11:0] add_signext_117; // sfix12
  wire signed [12:0] add_temp_58; // sfix13
  wire signed [11:0] sum60; // sfix12
  wire signed [11:0] add_signext_118; // sfix12
  wire signed [11:0] add_signext_119; // sfix12
  wire signed [12:0] add_temp_59; // sfix13
  wire signed [11:0] sum61; // sfix12
  wire signed [11:0] add_signext_120; // sfix12
  wire signed [11:0] add_signext_121; // sfix12
  wire signed [12:0] add_temp_60; // sfix13
  wire signed [11:0] sum62; // sfix12
  wire signed [11:0] add_signext_122; // sfix12
  wire signed [11:0] add_signext_123; // sfix12
  wire signed [12:0] add_temp_61; // sfix13
  wire signed [11:0] sum63; // sfix12
  wire signed [11:0] add_signext_124; // sfix12
  wire signed [11:0] add_signext_125; // sfix12
  wire signed [12:0] add_temp_62; // sfix13
  wire signed [11:0] sum64; // sfix12
  wire signed [11:0] add_signext_126; // sfix12
  wire signed [11:0] add_signext_127; // sfix12
  wire signed [12:0] add_temp_63; // sfix13
  wire signed [11:0] sum65; // sfix12
  wire signed [11:0] add_signext_128; // sfix12
  wire signed [11:0] add_signext_129; // sfix12
  wire signed [12:0] add_temp_64; // sfix13
  wire signed [11:0] sum66; // sfix12
  wire signed [11:0] add_signext_130; // sfix12
  wire signed [11:0] add_signext_131; // sfix12
  wire signed [12:0] add_temp_65; // sfix13
  wire signed [11:0] sum67; // sfix12
  wire signed [11:0] add_signext_132; // sfix12
  wire signed [11:0] add_signext_133; // sfix12
  wire signed [12:0] add_temp_66; // sfix13
  wire signed [11:0] sum68; // sfix12
  wire signed [11:0] add_signext_134; // sfix12
  wire signed [11:0] add_signext_135; // sfix12
  wire signed [12:0] add_temp_67; // sfix13
  wire signed [11:0] sum69; // sfix12
  wire signed [11:0] add_signext_136; // sfix12
  wire signed [11:0] add_signext_137; // sfix12
  wire signed [12:0] add_temp_68; // sfix13
  wire signed [11:0] sum70; // sfix12
  wire signed [11:0] add_signext_138; // sfix12
  wire signed [11:0] add_signext_139; // sfix12
  wire signed [12:0] add_temp_69; // sfix13
  wire signed [11:0] sum71; // sfix12
  wire signed [11:0] add_signext_140; // sfix12
  wire signed [11:0] add_signext_141; // sfix12
  wire signed [12:0] add_temp_70; // sfix13
  wire signed [11:0] sum72; // sfix12
  wire signed [11:0] add_signext_142; // sfix12
  wire signed [11:0] add_signext_143; // sfix12
  wire signed [12:0] add_temp_71; // sfix13
  wire signed [11:0] sum73; // sfix12
  wire signed [11:0] add_signext_144; // sfix12
  wire signed [11:0] add_signext_145; // sfix12
  wire signed [12:0] add_temp_72; // sfix13
  wire signed [11:0] sum74; // sfix12
  wire signed [11:0] add_signext_146; // sfix12
  wire signed [11:0] add_signext_147; // sfix12
  wire signed [12:0] add_temp_73; // sfix13
  wire signed [11:0] sum75; // sfix12
  wire signed [11:0] add_signext_148; // sfix12
  wire signed [11:0] add_signext_149; // sfix12
  wire signed [12:0] add_temp_74; // sfix13
  wire signed [11:0] sum76; // sfix12
  wire signed [11:0] add_signext_150; // sfix12
  wire signed [11:0] add_signext_151; // sfix12
  wire signed [12:0] add_temp_75; // sfix13
  wire signed [11:0] sum77; // sfix12
  wire signed [11:0] add_signext_152; // sfix12
  wire signed [11:0] add_signext_153; // sfix12
  wire signed [12:0] add_temp_76; // sfix13
  wire signed [11:0] sum78; // sfix12
  wire signed [11:0] add_signext_154; // sfix12
  wire signed [11:0] add_signext_155; // sfix12
  wire signed [12:0] add_temp_77; // sfix13
  wire signed [11:0] sum79; // sfix12
  wire signed [11:0] add_signext_156; // sfix12
  wire signed [11:0] add_signext_157; // sfix12
  wire signed [12:0] add_temp_78; // sfix13
  wire signed [11:0] sum80; // sfix12
  wire signed [11:0] add_signext_158; // sfix12
  wire signed [11:0] add_signext_159; // sfix12
  wire signed [12:0] add_temp_79; // sfix13
  wire signed [11:0] sum81; // sfix12
  wire signed [11:0] add_signext_160; // sfix12
  wire signed [11:0] add_signext_161; // sfix12
  wire signed [12:0] add_temp_80; // sfix13
  wire signed [11:0] sum82; // sfix12
  wire signed [11:0] add_signext_162; // sfix12
  wire signed [11:0] add_signext_163; // sfix12
  wire signed [12:0] add_temp_81; // sfix13
  wire signed [11:0] sum83; // sfix12
  wire signed [11:0] add_signext_164; // sfix12
  wire signed [11:0] add_signext_165; // sfix12
  wire signed [12:0] add_temp_82; // sfix13
  wire signed [11:0] sum84; // sfix12
  wire signed [11:0] add_signext_166; // sfix12
  wire signed [11:0] add_signext_167; // sfix12
  wire signed [12:0] add_temp_83; // sfix13
  wire signed [11:0] sum85; // sfix12
  wire signed [11:0] add_signext_168; // sfix12
  wire signed [11:0] add_signext_169; // sfix12
  wire signed [12:0] add_temp_84; // sfix13
  wire signed [11:0] sum86; // sfix12
  wire signed [11:0] add_signext_170; // sfix12
  wire signed [11:0] add_signext_171; // sfix12
  wire signed [12:0] add_temp_85; // sfix13
  wire signed [11:0] sum87; // sfix12
  wire signed [11:0] add_signext_172; // sfix12
  wire signed [11:0] add_signext_173; // sfix12
  wire signed [12:0] add_temp_86; // sfix13
  wire signed [11:0] sum88; // sfix12
  wire signed [11:0] add_signext_174; // sfix12
  wire signed [11:0] add_signext_175; // sfix12
  wire signed [12:0] add_temp_87; // sfix13
  wire signed [11:0] sum89; // sfix12
  wire signed [11:0] add_signext_176; // sfix12
  wire signed [11:0] add_signext_177; // sfix12
  wire signed [12:0] add_temp_88; // sfix13
  wire signed [11:0] sum90; // sfix12
  wire signed [11:0] add_signext_178; // sfix12
  wire signed [11:0] add_signext_179; // sfix12
  wire signed [12:0] add_temp_89; // sfix13
  wire signed [11:0] sum91; // sfix12
  wire signed [11:0] add_signext_180; // sfix12
  wire signed [11:0] add_signext_181; // sfix12
  wire signed [12:0] add_temp_90; // sfix13
  wire signed [11:0] sum92; // sfix12
  wire signed [11:0] add_signext_182; // sfix12
  wire signed [11:0] add_signext_183; // sfix12
  wire signed [12:0] add_temp_91; // sfix13
  wire signed [11:0] sum93; // sfix12
  wire signed [11:0] add_signext_184; // sfix12
  wire signed [11:0] add_signext_185; // sfix12
  wire signed [12:0] add_temp_92; // sfix13
  wire signed [11:0] sum94; // sfix12
  wire signed [11:0] add_signext_186; // sfix12
  wire signed [11:0] add_signext_187; // sfix12
  wire signed [12:0] add_temp_93; // sfix13
  wire signed [11:0] sum95; // sfix12
  wire signed [11:0] add_signext_188; // sfix12
  wire signed [11:0] add_signext_189; // sfix12
  wire signed [12:0] add_temp_94; // sfix13
  wire signed [11:0] sum96; // sfix12
  wire signed [11:0] add_signext_190; // sfix12
  wire signed [11:0] add_signext_191; // sfix12
  wire signed [12:0] add_temp_95; // sfix13
  wire signed [11:0] sum97; // sfix12
  wire signed [11:0] add_signext_192; // sfix12
  wire signed [11:0] add_signext_193; // sfix12
  wire signed [12:0] add_temp_96; // sfix13
  wire signed [11:0] sum98; // sfix12
  wire signed [11:0] add_signext_194; // sfix12
  wire signed [11:0] add_signext_195; // sfix12
  wire signed [12:0] add_temp_97; // sfix13
  wire signed [11:0] sum99; // sfix12
  wire signed [11:0] add_signext_196; // sfix12
  wire signed [11:0] add_signext_197; // sfix12
  wire signed [12:0] add_temp_98; // sfix13
  wire signed [11:0] sum100; // sfix12
  wire signed [11:0] add_signext_198; // sfix12
  wire signed [11:0] add_signext_199; // sfix12
  wire signed [12:0] add_temp_99; // sfix13
  wire signed [11:0] sum101; // sfix12
  wire signed [11:0] add_signext_200; // sfix12
  wire signed [11:0] add_signext_201; // sfix12
  wire signed [12:0] add_temp_100; // sfix13
  wire signed [11:0] sum102; // sfix12
  wire signed [11:0] add_signext_202; // sfix12
  wire signed [11:0] add_signext_203; // sfix12
  wire signed [12:0] add_temp_101; // sfix13
  wire signed [11:0] sum103; // sfix12
  wire signed [11:0] add_signext_204; // sfix12
  wire signed [11:0] add_signext_205; // sfix12
  wire signed [12:0] add_temp_102; // sfix13
  wire signed [11:0] sum104; // sfix12
  wire signed [11:0] add_signext_206; // sfix12
  wire signed [11:0] add_signext_207; // sfix12
  wire signed [12:0] add_temp_103; // sfix13
  wire signed [11:0] sum105; // sfix12
  wire signed [11:0] add_signext_208; // sfix12
  wire signed [11:0] add_signext_209; // sfix12
  wire signed [12:0] add_temp_104; // sfix13
  wire signed [11:0] sum106; // sfix12
  wire signed [11:0] add_signext_210; // sfix12
  wire signed [11:0] add_signext_211; // sfix12
  wire signed [12:0] add_temp_105; // sfix13
  wire signed [11:0] sum107; // sfix12
  wire signed [11:0] add_signext_212; // sfix12
  wire signed [11:0] add_signext_213; // sfix12
  wire signed [12:0] add_temp_106; // sfix13
  wire signed [11:0] sum108; // sfix12
  wire signed [11:0] add_signext_214; // sfix12
  wire signed [11:0] add_signext_215; // sfix12
  wire signed [12:0] add_temp_107; // sfix13
  wire signed [11:0] sum109; // sfix12
  wire signed [11:0] add_signext_216; // sfix12
  wire signed [11:0] add_signext_217; // sfix12
  wire signed [12:0] add_temp_108; // sfix13
  wire signed [11:0] sum110; // sfix12
  wire signed [11:0] add_signext_218; // sfix12
  wire signed [11:0] add_signext_219; // sfix12
  wire signed [12:0] add_temp_109; // sfix13
  wire signed [11:0] sum111; // sfix12
  wire signed [11:0] add_signext_220; // sfix12
  wire signed [11:0] add_signext_221; // sfix12
  wire signed [12:0] add_temp_110; // sfix13
  wire signed [11:0] sum112; // sfix12
  wire signed [11:0] add_signext_222; // sfix12
  wire signed [11:0] add_signext_223; // sfix12
  wire signed [12:0] add_temp_111; // sfix13
  wire signed [11:0] sum113; // sfix12
  wire signed [11:0] add_signext_224; // sfix12
  wire signed [11:0] add_signext_225; // sfix12
  wire signed [12:0] add_temp_112; // sfix13
  wire signed [11:0] sum114; // sfix12
  wire signed [11:0] add_signext_226; // sfix12
  wire signed [11:0] add_signext_227; // sfix12
  wire signed [12:0] add_temp_113; // sfix13
  wire signed [11:0] sum115; // sfix12
  wire signed [11:0] add_signext_228; // sfix12
  wire signed [11:0] add_signext_229; // sfix12
  wire signed [12:0] add_temp_114; // sfix13
  wire signed [11:0] sum116; // sfix12
  wire signed [11:0] add_signext_230; // sfix12
  wire signed [11:0] add_signext_231; // sfix12
  wire signed [12:0] add_temp_115; // sfix13
  wire signed [11:0] sum117; // sfix12
  wire signed [11:0] add_signext_232; // sfix12
  wire signed [11:0] add_signext_233; // sfix12
  wire signed [12:0] add_temp_116; // sfix13
  wire signed [11:0] sum118; // sfix12
  wire signed [11:0] add_signext_234; // sfix12
  wire signed [11:0] add_signext_235; // sfix12
  wire signed [12:0] add_temp_117; // sfix13
  wire signed [11:0] sum119; // sfix12
  wire signed [11:0] add_signext_236; // sfix12
  wire signed [11:0] add_signext_237; // sfix12
  wire signed [12:0] add_temp_118; // sfix13
  wire signed [11:0] sum120; // sfix12
  wire signed [11:0] add_signext_238; // sfix12
  wire signed [11:0] add_signext_239; // sfix12
  wire signed [12:0] add_temp_119; // sfix13
  wire signed [11:0] sum121; // sfix12
  wire signed [11:0] add_signext_240; // sfix12
  wire signed [11:0] add_signext_241; // sfix12
  wire signed [12:0] add_temp_120; // sfix13
  wire signed [11:0] sum122; // sfix12
  wire signed [11:0] add_signext_242; // sfix12
  wire signed [11:0] add_signext_243; // sfix12
  wire signed [12:0] add_temp_121; // sfix13
  wire signed [11:0] sum123; // sfix12
  wire signed [11:0] add_signext_244; // sfix12
  wire signed [11:0] add_signext_245; // sfix12
  wire signed [12:0] add_temp_122; // sfix13
  wire signed [11:0] sum124; // sfix12
  wire signed [11:0] add_signext_246; // sfix12
  wire signed [11:0] add_signext_247; // sfix12
  wire signed [12:0] add_temp_123; // sfix13
  reg  signed [11:0] output_register; // sfix12

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
        delay_pipeline[43] <= 0;
        delay_pipeline[44] <= 0;
        delay_pipeline[45] <= 0;
        delay_pipeline[46] <= 0;
        delay_pipeline[47] <= 0;
        delay_pipeline[48] <= 0;
        delay_pipeline[49] <= 0;
        delay_pipeline[50] <= 0;
        delay_pipeline[51] <= 0;
        delay_pipeline[52] <= 0;
        delay_pipeline[53] <= 0;
        delay_pipeline[54] <= 0;
        delay_pipeline[55] <= 0;
        delay_pipeline[56] <= 0;
        delay_pipeline[57] <= 0;
        delay_pipeline[58] <= 0;
        delay_pipeline[59] <= 0;
        delay_pipeline[60] <= 0;
        delay_pipeline[61] <= 0;
        delay_pipeline[62] <= 0;
        delay_pipeline[63] <= 0;
        delay_pipeline[64] <= 0;
        delay_pipeline[65] <= 0;
        delay_pipeline[66] <= 0;
        delay_pipeline[67] <= 0;
        delay_pipeline[68] <= 0;
        delay_pipeline[69] <= 0;
        delay_pipeline[70] <= 0;
        delay_pipeline[71] <= 0;
        delay_pipeline[72] <= 0;
        delay_pipeline[73] <= 0;
        delay_pipeline[74] <= 0;
        delay_pipeline[75] <= 0;
        delay_pipeline[76] <= 0;
        delay_pipeline[77] <= 0;
        delay_pipeline[78] <= 0;
        delay_pipeline[79] <= 0;
        delay_pipeline[80] <= 0;
        delay_pipeline[81] <= 0;
        delay_pipeline[82] <= 0;
        delay_pipeline[83] <= 0;
        delay_pipeline[84] <= 0;
        delay_pipeline[85] <= 0;
        delay_pipeline[86] <= 0;
        delay_pipeline[87] <= 0;
        delay_pipeline[88] <= 0;
        delay_pipeline[89] <= 0;
        delay_pipeline[90] <= 0;
        delay_pipeline[91] <= 0;
        delay_pipeline[92] <= 0;
        delay_pipeline[93] <= 0;
        delay_pipeline[94] <= 0;
        delay_pipeline[95] <= 0;
        delay_pipeline[96] <= 0;
        delay_pipeline[97] <= 0;
        delay_pipeline[98] <= 0;
        delay_pipeline[99] <= 0;
        delay_pipeline[100] <= 0;
        delay_pipeline[101] <= 0;
        delay_pipeline[102] <= 0;
        delay_pipeline[103] <= 0;
        delay_pipeline[104] <= 0;
        delay_pipeline[105] <= 0;
        delay_pipeline[106] <= 0;
        delay_pipeline[107] <= 0;
        delay_pipeline[108] <= 0;
        delay_pipeline[109] <= 0;
        delay_pipeline[110] <= 0;
        delay_pipeline[111] <= 0;
        delay_pipeline[112] <= 0;
        delay_pipeline[113] <= 0;
        delay_pipeline[114] <= 0;
        delay_pipeline[115] <= 0;
        delay_pipeline[116] <= 0;
        delay_pipeline[117] <= 0;
        delay_pipeline[118] <= 0;
        delay_pipeline[119] <= 0;
        delay_pipeline[120] <= 0;
        delay_pipeline[121] <= 0;
        delay_pipeline[122] <= 0;
        delay_pipeline[123] <= 0;
        delay_pipeline[124] <= 0;
        delay_pipeline[125] <= 0;
        delay_pipeline[126] <= 0;
        delay_pipeline[127] <= 0;
        delay_pipeline[128] <= 0;
        delay_pipeline[129] <= 0;
        delay_pipeline[130] <= 0;
        delay_pipeline[131] <= 0;
        delay_pipeline[132] <= 0;
        delay_pipeline[133] <= 0;
        delay_pipeline[134] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
          delay_pipeline[43] <= delay_pipeline[42];
          delay_pipeline[44] <= delay_pipeline[43];
          delay_pipeline[45] <= delay_pipeline[44];
          delay_pipeline[46] <= delay_pipeline[45];
          delay_pipeline[47] <= delay_pipeline[46];
          delay_pipeline[48] <= delay_pipeline[47];
          delay_pipeline[49] <= delay_pipeline[48];
          delay_pipeline[50] <= delay_pipeline[49];
          delay_pipeline[51] <= delay_pipeline[50];
          delay_pipeline[52] <= delay_pipeline[51];
          delay_pipeline[53] <= delay_pipeline[52];
          delay_pipeline[54] <= delay_pipeline[53];
          delay_pipeline[55] <= delay_pipeline[54];
          delay_pipeline[56] <= delay_pipeline[55];
          delay_pipeline[57] <= delay_pipeline[56];
          delay_pipeline[58] <= delay_pipeline[57];
          delay_pipeline[59] <= delay_pipeline[58];
          delay_pipeline[60] <= delay_pipeline[59];
          delay_pipeline[61] <= delay_pipeline[60];
          delay_pipeline[62] <= delay_pipeline[61];
          delay_pipeline[63] <= delay_pipeline[62];
          delay_pipeline[64] <= delay_pipeline[63];
          delay_pipeline[65] <= delay_pipeline[64];
          delay_pipeline[66] <= delay_pipeline[65];
          delay_pipeline[67] <= delay_pipeline[66];
          delay_pipeline[68] <= delay_pipeline[67];
          delay_pipeline[69] <= delay_pipeline[68];
          delay_pipeline[70] <= delay_pipeline[69];
          delay_pipeline[71] <= delay_pipeline[70];
          delay_pipeline[72] <= delay_pipeline[71];
          delay_pipeline[73] <= delay_pipeline[72];
          delay_pipeline[74] <= delay_pipeline[73];
          delay_pipeline[75] <= delay_pipeline[74];
          delay_pipeline[76] <= delay_pipeline[75];
          delay_pipeline[77] <= delay_pipeline[76];
          delay_pipeline[78] <= delay_pipeline[77];
          delay_pipeline[79] <= delay_pipeline[78];
          delay_pipeline[80] <= delay_pipeline[79];
          delay_pipeline[81] <= delay_pipeline[80];
          delay_pipeline[82] <= delay_pipeline[81];
          delay_pipeline[83] <= delay_pipeline[82];
          delay_pipeline[84] <= delay_pipeline[83];
          delay_pipeline[85] <= delay_pipeline[84];
          delay_pipeline[86] <= delay_pipeline[85];
          delay_pipeline[87] <= delay_pipeline[86];
          delay_pipeline[88] <= delay_pipeline[87];
          delay_pipeline[89] <= delay_pipeline[88];
          delay_pipeline[90] <= delay_pipeline[89];
          delay_pipeline[91] <= delay_pipeline[90];
          delay_pipeline[92] <= delay_pipeline[91];
          delay_pipeline[93] <= delay_pipeline[92];
          delay_pipeline[94] <= delay_pipeline[93];
          delay_pipeline[95] <= delay_pipeline[94];
          delay_pipeline[96] <= delay_pipeline[95];
          delay_pipeline[97] <= delay_pipeline[96];
          delay_pipeline[98] <= delay_pipeline[97];
          delay_pipeline[99] <= delay_pipeline[98];
          delay_pipeline[100] <= delay_pipeline[99];
          delay_pipeline[101] <= delay_pipeline[100];
          delay_pipeline[102] <= delay_pipeline[101];
          delay_pipeline[103] <= delay_pipeline[102];
          delay_pipeline[104] <= delay_pipeline[103];
          delay_pipeline[105] <= delay_pipeline[104];
          delay_pipeline[106] <= delay_pipeline[105];
          delay_pipeline[107] <= delay_pipeline[106];
          delay_pipeline[108] <= delay_pipeline[107];
          delay_pipeline[109] <= delay_pipeline[108];
          delay_pipeline[110] <= delay_pipeline[109];
          delay_pipeline[111] <= delay_pipeline[110];
          delay_pipeline[112] <= delay_pipeline[111];
          delay_pipeline[113] <= delay_pipeline[112];
          delay_pipeline[114] <= delay_pipeline[113];
          delay_pipeline[115] <= delay_pipeline[114];
          delay_pipeline[116] <= delay_pipeline[115];
          delay_pipeline[117] <= delay_pipeline[116];
          delay_pipeline[118] <= delay_pipeline[117];
          delay_pipeline[119] <= delay_pipeline[118];
          delay_pipeline[120] <= delay_pipeline[119];
          delay_pipeline[121] <= delay_pipeline[120];
          delay_pipeline[122] <= delay_pipeline[121];
          delay_pipeline[123] <= delay_pipeline[122];
          delay_pipeline[124] <= delay_pipeline[123];
          delay_pipeline[125] <= delay_pipeline[124];
          delay_pipeline[126] <= delay_pipeline[125];
          delay_pipeline[127] <= delay_pipeline[126];
          delay_pipeline[128] <= delay_pipeline[127];
          delay_pipeline[129] <= delay_pipeline[128];
          delay_pipeline[130] <= delay_pipeline[129];
          delay_pipeline[131] <= delay_pipeline[130];
          delay_pipeline[132] <= delay_pipeline[131];
          delay_pipeline[133] <= delay_pipeline[132];
          delay_pipeline[134] <= delay_pipeline[133];
        end
      end
    end // Delay_Pipeline_process


  assign mul_temp = delay_pipeline[134] * coeff135;
  assign product135 = (mul_temp[22:0] + {mul_temp[11], {10{~mul_temp[11]}}})>>>11;

  assign mul_temp_1 = delay_pipeline[133] * coeff134;
  assign product134 = (mul_temp_1[22:0] + {mul_temp_1[11], {10{~mul_temp_1[11]}}})>>>11;

  assign mul_temp_2 = delay_pipeline[132] * coeff133;
  assign product133 = (mul_temp_2[22:0] + {mul_temp_2[11], {10{~mul_temp_2[11]}}})>>>11;

  assign mul_temp_3 = delay_pipeline[131] * coeff132;
  assign product132 = (mul_temp_3[22:0] + {mul_temp_3[11], {10{~mul_temp_3[11]}}})>>>11;

  assign mul_temp_4 = delay_pipeline[130] * coeff131;
  assign product131 = (mul_temp_4[22:0] + {mul_temp_4[11], {10{~mul_temp_4[11]}}})>>>11;

  assign mulpwr2_temp = (delay_pipeline[124]==12'b100000000000) ? $signed({1'b0, delay_pipeline[124]}) : -delay_pipeline[124];

  assign product125 = ({{10{mulpwr2_temp[12]}}, mulpwr2_temp[12:0]} + {mulpwr2_temp[11], {10{~mulpwr2_temp[11]}}})>>>11;

  assign mulpwr2_temp_1 = (delay_pipeline[123]==12'b100000000000) ? $signed({1'b0, delay_pipeline[123]}) : -delay_pipeline[123];

  assign product124 = ({{9{mulpwr2_temp_1[12]}}, mulpwr2_temp_1[12:0]} + {mulpwr2_temp_1[10], {9{~mulpwr2_temp_1[10]}}})>>>10;

  assign mulpwr2_temp_2 = (delay_pipeline[122]==12'b100000000000) ? $signed({1'b0, delay_pipeline[122]}) : -delay_pipeline[122];

  assign product123 = ({{10{mulpwr2_temp_2[12]}}, mulpwr2_temp_2[12:0]} + {mulpwr2_temp_2[11], {10{~mulpwr2_temp_2[11]}}})>>>11;

  assign product122 = ({{11{delay_pipeline[121][11]}}, delay_pipeline[121][11:0]} + {delay_pipeline[121][11], {10{~delay_pipeline[121][11]}}})>>>11;

  assign mul_temp_5 = delay_pipeline[120] * coeff121;
  assign product121 = (mul_temp_5[22:0] + {mul_temp_5[11], {10{~mul_temp_5[11]}}})>>>11;

  assign product120 = ({{9{delay_pipeline[119][11]}}, delay_pipeline[119][11:0]} + {delay_pipeline[119][9], {8{~delay_pipeline[119][9]}}})>>>9;

  assign product119 = ({{11{delay_pipeline[118][11]}}, delay_pipeline[118][11:0]} + {delay_pipeline[118][11], {10{~delay_pipeline[118][11]}}})>>>11;

  assign mulpwr2_temp_3 = (delay_pipeline[117]==12'b100000000000) ? $signed({1'b0, delay_pipeline[117]}) : -delay_pipeline[117];

  assign product118 = ({{8{mulpwr2_temp_3[12]}}, mulpwr2_temp_3[12:0]} + {mulpwr2_temp_3[9], {8{~mulpwr2_temp_3[9]}}})>>>9;

  assign mul_temp_6 = delay_pipeline[116] * coeff117;
  assign product117 = (mul_temp_6[22:0] + {mul_temp_6[11], {10{~mul_temp_6[11]}}})>>>11;

  assign mul_temp_7 = delay_pipeline[115] * coeff116;
  assign product116 = (mul_temp_7[22:0] + {mul_temp_7[11], {10{~mul_temp_7[11]}}})>>>11;

  assign product115 = ({{10{delay_pipeline[114][11]}}, delay_pipeline[114][11:0]} + {delay_pipeline[114][10], {9{~delay_pipeline[114][10]}}})>>>10;

  assign mul_temp_8 = delay_pipeline[113] * coeff114;
  assign product114 = (mul_temp_8[22:0] + {mul_temp_8[11], {10{~mul_temp_8[11]}}})>>>11;

  assign mul_temp_9 = delay_pipeline[112] * coeff113;
  assign product113 = (mul_temp_9[22:0] + {mul_temp_9[11], {10{~mul_temp_9[11]}}})>>>11;

  assign mul_temp_10 = delay_pipeline[111] * coeff112;
  assign product112 = (mul_temp_10[22:0] + {mul_temp_10[11], {10{~mul_temp_10[11]}}})>>>11;

  assign mul_temp_11 = delay_pipeline[110] * coeff111;
  assign product111 = (mul_temp_11[22:0] + {mul_temp_11[11], {10{~mul_temp_11[11]}}})>>>11;

  assign mulpwr2_temp_4 = (delay_pipeline[109]==12'b100000000000) ? $signed({1'b0, delay_pipeline[109]}) : -delay_pipeline[109];

  assign product110 = ({{6{mulpwr2_temp_4[12]}}, mulpwr2_temp_4[12:0]} + {mulpwr2_temp_4[7], {6{~mulpwr2_temp_4[7]}}})>>>7;

  assign mul_temp_12 = delay_pipeline[108] * coeff109;
  assign product109 = (mul_temp_12[22:0] + {mul_temp_12[11], {10{~mul_temp_12[11]}}})>>>11;

  assign product108 = ({{9{delay_pipeline[107][11]}}, delay_pipeline[107][11:0]} + {delay_pipeline[107][9], {8{~delay_pipeline[107][9]}}})>>>9;

  assign mul_temp_13 = delay_pipeline[106] * coeff107;
  assign product107 = (mul_temp_13[22:0] + {mul_temp_13[11], {10{~mul_temp_13[11]}}})>>>11;

  assign mul_temp_14 = delay_pipeline[105] * coeff106;
  assign product106 = (mul_temp_14[22:0] + {mul_temp_14[11], {10{~mul_temp_14[11]}}})>>>11;

  assign mul_temp_15 = delay_pipeline[104] * coeff105;
  assign product105 = (mul_temp_15[22:0] + {mul_temp_15[11], {10{~mul_temp_15[11]}}})>>>11;

  assign mulpwr2_temp_5 = (delay_pipeline[103]==12'b100000000000) ? $signed({1'b0, delay_pipeline[103]}) : -delay_pipeline[103];

  assign product104 = ({{6{mulpwr2_temp_5[12]}}, mulpwr2_temp_5[12:0]} + {mulpwr2_temp_5[7], {6{~mulpwr2_temp_5[7]}}})>>>7;

  assign mul_temp_16 = delay_pipeline[102] * coeff103;
  assign product103 = (mul_temp_16[22:0] + {mul_temp_16[11], {10{~mul_temp_16[11]}}})>>>11;

  assign mul_temp_17 = delay_pipeline[101] * coeff102;
  assign product102 = (mul_temp_17[22:0] + {mul_temp_17[11], {10{~mul_temp_17[11]}}})>>>11;

  assign mul_temp_18 = delay_pipeline[100] * coeff101;
  assign product101 = (mul_temp_18[22:0] + {mul_temp_18[11], {10{~mul_temp_18[11]}}})>>>11;

  assign mul_temp_19 = delay_pipeline[99] * coeff100;
  assign product100 = (mul_temp_19[22:0] + {mul_temp_19[11], {10{~mul_temp_19[11]}}})>>>11;

  assign mul_temp_20 = delay_pipeline[98] * coeff99;
  assign product99 = (mul_temp_20[22:0] + {mul_temp_20[11], {10{~mul_temp_20[11]}}})>>>11;

  assign product98 = ({{8{delay_pipeline[97][11]}}, delay_pipeline[97][11:0]} + {delay_pipeline[97][8], {7{~delay_pipeline[97][8]}}})>>>8;

  assign mul_temp_21 = delay_pipeline[96] * coeff97;
  assign product97 = (mul_temp_21[22:0] + {mul_temp_21[11], {10{~mul_temp_21[11]}}})>>>11;

  assign mul_temp_22 = delay_pipeline[95] * coeff96;
  assign product96 = (mul_temp_22[22:0] + {mul_temp_22[11], {10{~mul_temp_22[11]}}})>>>11;

  assign mul_temp_23 = delay_pipeline[94] * coeff95;
  assign product95 = (mul_temp_23[22:0] + {mul_temp_23[11], {10{~mul_temp_23[11]}}})>>>11;

  assign mul_temp_24 = delay_pipeline[93] * coeff94;
  assign product94 = (mul_temp_24[22:0] + {mul_temp_24[11], {10{~mul_temp_24[11]}}})>>>11;

  assign mul_temp_25 = delay_pipeline[92] * coeff93;
  assign product93 = (mul_temp_25[22:0] + {mul_temp_25[11], {10{~mul_temp_25[11]}}})>>>11;

  assign mul_temp_26 = delay_pipeline[91] * coeff92;
  assign product92 = (mul_temp_26[22:0] + {mul_temp_26[11], {10{~mul_temp_26[11]}}})>>>11;

  assign mul_temp_27 = delay_pipeline[90] * coeff91;
  assign product91 = (mul_temp_27[22:0] + {mul_temp_27[11], {10{~mul_temp_27[11]}}})>>>11;

  assign mul_temp_28 = delay_pipeline[89] * coeff90;
  assign product90 = (mul_temp_28[22:0] + {mul_temp_28[11], {10{~mul_temp_28[11]}}})>>>11;

  assign mul_temp_29 = delay_pipeline[88] * coeff89;
  assign product89 = (mul_temp_29[22:0] + {mul_temp_29[11], {10{~mul_temp_29[11]}}})>>>11;

  assign mul_temp_30 = delay_pipeline[87] * coeff88;
  assign product88 = (mul_temp_30[22:0] + {mul_temp_30[11], {10{~mul_temp_30[11]}}})>>>11;

  assign mul_temp_31 = delay_pipeline[86] * coeff87;
  assign product87 = (mul_temp_31[22:0] + {mul_temp_31[11], {10{~mul_temp_31[11]}}})>>>11;

  assign mul_temp_32 = delay_pipeline[85] * coeff86;
  assign product86 = (mul_temp_32[22:0] + {mul_temp_32[11], {10{~mul_temp_32[11]}}})>>>11;

  assign mul_temp_33 = delay_pipeline[84] * coeff85;
  assign product85 = (mul_temp_33[22:0] + {mul_temp_33[11], {10{~mul_temp_33[11]}}})>>>11;

  assign mul_temp_34 = delay_pipeline[83] * coeff84;
  assign product84 = (mul_temp_34[22:0] + {mul_temp_34[11], {10{~mul_temp_34[11]}}})>>>11;

  assign mul_temp_35 = delay_pipeline[82] * coeff83;
  assign product83 = (mul_temp_35[22:0] + {mul_temp_35[11], {10{~mul_temp_35[11]}}})>>>11;

  assign mul_temp_36 = delay_pipeline[81] * coeff82;
  assign product82 = (mul_temp_36[22:0] + {mul_temp_36[11], {10{~mul_temp_36[11]}}})>>>11;

  assign mul_temp_37 = delay_pipeline[80] * coeff81;
  assign product81 = (mul_temp_37[22:0] + {mul_temp_37[11], {10{~mul_temp_37[11]}}})>>>11;

  assign mul_temp_38 = delay_pipeline[79] * coeff80;
  assign product80 = (mul_temp_38[22:0] + {mul_temp_38[11], {10{~mul_temp_38[11]}}})>>>11;

  assign mul_temp_39 = delay_pipeline[78] * coeff79;
  assign product79 = (mul_temp_39[22:0] + {mul_temp_39[11], {10{~mul_temp_39[11]}}})>>>11;

  assign mul_temp_40 = delay_pipeline[77] * coeff78;
  assign product78 = (mul_temp_40[22:0] + {mul_temp_40[11], {10{~mul_temp_40[11]}}})>>>11;

  assign mul_temp_41 = delay_pipeline[76] * coeff77;
  assign product77 = (mul_temp_41[22:0] + {mul_temp_41[11], {10{~mul_temp_41[11]}}})>>>11;

  assign mul_temp_42 = delay_pipeline[75] * coeff76;
  assign product76 = (mul_temp_42[22:0] + {mul_temp_42[11], {10{~mul_temp_42[11]}}})>>>11;

  assign mul_temp_43 = delay_pipeline[74] * coeff75;
  assign product75 = (mul_temp_43[22:0] + {mul_temp_43[11], {10{~mul_temp_43[11]}}})>>>11;

  assign mul_temp_44 = delay_pipeline[73] * coeff74;
  assign product74 = (mul_temp_44[22:0] + {mul_temp_44[11], {10{~mul_temp_44[11]}}})>>>11;

  assign mul_temp_45 = delay_pipeline[72] * coeff73;
  assign product73 = (mul_temp_45[22:0] + {mul_temp_45[11], {10{~mul_temp_45[11]}}})>>>11;

  assign mul_temp_46 = delay_pipeline[71] * coeff72;
  assign product72 = (mul_temp_46[22:0] + {mul_temp_46[11], {10{~mul_temp_46[11]}}})>>>11;

  assign mul_temp_47 = delay_pipeline[70] * coeff71;
  assign product71 = (mul_temp_47[22:0] + {mul_temp_47[11], {10{~mul_temp_47[11]}}})>>>11;

  assign product70 = ({{7{delay_pipeline[69][11]}}, delay_pipeline[69][11:0]} + {delay_pipeline[69][7], {6{~delay_pipeline[69][7]}}})>>>7;

  assign mul_temp_48 = delay_pipeline[68] * coeff69;
  assign product69 = (mul_temp_48[22:0] + {mul_temp_48[11], {10{~mul_temp_48[11]}}})>>>11;

  assign mul_temp_49 = delay_pipeline[67] * coeff68;
  assign product68 = (mul_temp_49[22:0] + {mul_temp_49[11], {10{~mul_temp_49[11]}}})>>>11;

  assign mul_temp_50 = delay_pipeline[66] * coeff67;
  assign product67 = (mul_temp_50[22:0] + {mul_temp_50[11], {10{~mul_temp_50[11]}}})>>>11;

  assign product66 = ({{7{delay_pipeline[65][11]}}, delay_pipeline[65][11:0]} + {delay_pipeline[65][7], {6{~delay_pipeline[65][7]}}})>>>7;

  assign mul_temp_51 = delay_pipeline[64] * coeff65;
  assign product65 = (mul_temp_51[22:0] + {mul_temp_51[11], {10{~mul_temp_51[11]}}})>>>11;

  assign mul_temp_52 = delay_pipeline[63] * coeff64;
  assign product64 = (mul_temp_52[22:0] + {mul_temp_52[11], {10{~mul_temp_52[11]}}})>>>11;

  assign mul_temp_53 = delay_pipeline[62] * coeff63;
  assign product63 = (mul_temp_53[22:0] + {mul_temp_53[11], {10{~mul_temp_53[11]}}})>>>11;

  assign mul_temp_54 = delay_pipeline[61] * coeff62;
  assign product62 = (mul_temp_54[22:0] + {mul_temp_54[11], {10{~mul_temp_54[11]}}})>>>11;

  assign mul_temp_55 = delay_pipeline[60] * coeff61;
  assign product61 = (mul_temp_55[22:0] + {mul_temp_55[11], {10{~mul_temp_55[11]}}})>>>11;

  assign mul_temp_56 = delay_pipeline[59] * coeff60;
  assign product60 = (mul_temp_56[22:0] + {mul_temp_56[11], {10{~mul_temp_56[11]}}})>>>11;

  assign mul_temp_57 = delay_pipeline[58] * coeff59;
  assign product59 = (mul_temp_57[22:0] + {mul_temp_57[11], {10{~mul_temp_57[11]}}})>>>11;

  assign mul_temp_58 = delay_pipeline[57] * coeff58;
  assign product58 = (mul_temp_58[22:0] + {mul_temp_58[11], {10{~mul_temp_58[11]}}})>>>11;

  assign mul_temp_59 = delay_pipeline[56] * coeff57;
  assign product57 = (mul_temp_59[22:0] + {mul_temp_59[11], {10{~mul_temp_59[11]}}})>>>11;

  assign mul_temp_60 = delay_pipeline[55] * coeff56;
  assign product56 = (mul_temp_60[22:0] + {mul_temp_60[11], {10{~mul_temp_60[11]}}})>>>11;

  assign mul_temp_61 = delay_pipeline[54] * coeff55;
  assign product55 = (mul_temp_61[22:0] + {mul_temp_61[11], {10{~mul_temp_61[11]}}})>>>11;

  assign mul_temp_62 = delay_pipeline[53] * coeff54;
  assign product54 = (mul_temp_62[22:0] + {mul_temp_62[11], {10{~mul_temp_62[11]}}})>>>11;

  assign mul_temp_63 = delay_pipeline[52] * coeff53;
  assign product53 = (mul_temp_63[22:0] + {mul_temp_63[11], {10{~mul_temp_63[11]}}})>>>11;

  assign mul_temp_64 = delay_pipeline[51] * coeff52;
  assign product52 = (mul_temp_64[22:0] + {mul_temp_64[11], {10{~mul_temp_64[11]}}})>>>11;

  assign mul_temp_65 = delay_pipeline[50] * coeff51;
  assign product51 = (mul_temp_65[22:0] + {mul_temp_65[11], {10{~mul_temp_65[11]}}})>>>11;

  assign mul_temp_66 = delay_pipeline[49] * coeff50;
  assign product50 = (mul_temp_66[22:0] + {mul_temp_66[11], {10{~mul_temp_66[11]}}})>>>11;

  assign mul_temp_67 = delay_pipeline[48] * coeff49;
  assign product49 = (mul_temp_67[22:0] + {mul_temp_67[11], {10{~mul_temp_67[11]}}})>>>11;

  assign mul_temp_68 = delay_pipeline[47] * coeff48;
  assign product48 = (mul_temp_68[22:0] + {mul_temp_68[11], {10{~mul_temp_68[11]}}})>>>11;

  assign mul_temp_69 = delay_pipeline[46] * coeff47;
  assign product47 = (mul_temp_69[22:0] + {mul_temp_69[11], {10{~mul_temp_69[11]}}})>>>11;

  assign mul_temp_70 = delay_pipeline[45] * coeff46;
  assign product46 = (mul_temp_70[22:0] + {mul_temp_70[11], {10{~mul_temp_70[11]}}})>>>11;

  assign mul_temp_71 = delay_pipeline[44] * coeff45;
  assign product45 = (mul_temp_71[22:0] + {mul_temp_71[11], {10{~mul_temp_71[11]}}})>>>11;

  assign mul_temp_72 = delay_pipeline[43] * coeff44;
  assign product44 = (mul_temp_72[22:0] + {mul_temp_72[11], {10{~mul_temp_72[11]}}})>>>11;

  assign mul_temp_73 = delay_pipeline[42] * coeff43;
  assign product43 = (mul_temp_73[22:0] + {mul_temp_73[11], {10{~mul_temp_73[11]}}})>>>11;

  assign mul_temp_74 = delay_pipeline[41] * coeff42;
  assign product42 = (mul_temp_74[22:0] + {mul_temp_74[11], {10{~mul_temp_74[11]}}})>>>11;

  assign mul_temp_75 = delay_pipeline[40] * coeff41;
  assign product41 = (mul_temp_75[22:0] + {mul_temp_75[11], {10{~mul_temp_75[11]}}})>>>11;

  assign mul_temp_76 = delay_pipeline[39] * coeff40;
  assign product40 = (mul_temp_76[22:0] + {mul_temp_76[11], {10{~mul_temp_76[11]}}})>>>11;

  assign mul_temp_77 = delay_pipeline[38] * coeff39;
  assign product39 = (mul_temp_77[22:0] + {mul_temp_77[11], {10{~mul_temp_77[11]}}})>>>11;

  assign product38 = ({{8{delay_pipeline[37][11]}}, delay_pipeline[37][11:0]} + {delay_pipeline[37][8], {7{~delay_pipeline[37][8]}}})>>>8;

  assign mul_temp_78 = delay_pipeline[36] * coeff37;
  assign product37 = (mul_temp_78[22:0] + {mul_temp_78[11], {10{~mul_temp_78[11]}}})>>>11;

  assign mul_temp_79 = delay_pipeline[35] * coeff36;
  assign product36 = (mul_temp_79[22:0] + {mul_temp_79[11], {10{~mul_temp_79[11]}}})>>>11;

  assign mul_temp_80 = delay_pipeline[34] * coeff35;
  assign product35 = (mul_temp_80[22:0] + {mul_temp_80[11], {10{~mul_temp_80[11]}}})>>>11;

  assign mul_temp_81 = delay_pipeline[33] * coeff34;
  assign product34 = (mul_temp_81[22:0] + {mul_temp_81[11], {10{~mul_temp_81[11]}}})>>>11;

  assign mul_temp_82 = delay_pipeline[32] * coeff33;
  assign product33 = (mul_temp_82[22:0] + {mul_temp_82[11], {10{~mul_temp_82[11]}}})>>>11;

  assign mulpwr2_temp_6 = (delay_pipeline[31]==12'b100000000000) ? $signed({1'b0, delay_pipeline[31]}) : -delay_pipeline[31];

  assign product32 = ({{6{mulpwr2_temp_6[12]}}, mulpwr2_temp_6[12:0]} + {mulpwr2_temp_6[7], {6{~mulpwr2_temp_6[7]}}})>>>7;

  assign mul_temp_83 = delay_pipeline[30] * coeff31;
  assign product31 = (mul_temp_83[22:0] + {mul_temp_83[11], {10{~mul_temp_83[11]}}})>>>11;

  assign mul_temp_84 = delay_pipeline[29] * coeff30;
  assign product30 = (mul_temp_84[22:0] + {mul_temp_84[11], {10{~mul_temp_84[11]}}})>>>11;

  assign mul_temp_85 = delay_pipeline[28] * coeff29;
  assign product29 = (mul_temp_85[22:0] + {mul_temp_85[11], {10{~mul_temp_85[11]}}})>>>11;

  assign product28 = ({{9{delay_pipeline[27][11]}}, delay_pipeline[27][11:0]} + {delay_pipeline[27][9], {8{~delay_pipeline[27][9]}}})>>>9;

  assign mul_temp_86 = delay_pipeline[26] * coeff27;
  assign product27 = (mul_temp_86[22:0] + {mul_temp_86[11], {10{~mul_temp_86[11]}}})>>>11;

  assign mulpwr2_temp_7 = (delay_pipeline[25]==12'b100000000000) ? $signed({1'b0, delay_pipeline[25]}) : -delay_pipeline[25];

  assign product26 = ({{6{mulpwr2_temp_7[12]}}, mulpwr2_temp_7[12:0]} + {mulpwr2_temp_7[7], {6{~mulpwr2_temp_7[7]}}})>>>7;

  assign mul_temp_87 = delay_pipeline[24] * coeff25;
  assign product25 = (mul_temp_87[22:0] + {mul_temp_87[11], {10{~mul_temp_87[11]}}})>>>11;

  assign mul_temp_88 = delay_pipeline[23] * coeff24;
  assign product24 = (mul_temp_88[22:0] + {mul_temp_88[11], {10{~mul_temp_88[11]}}})>>>11;

  assign mul_temp_89 = delay_pipeline[22] * coeff23;
  assign product23 = (mul_temp_89[22:0] + {mul_temp_89[11], {10{~mul_temp_89[11]}}})>>>11;

  assign mul_temp_90 = delay_pipeline[21] * coeff22;
  assign product22 = (mul_temp_90[22:0] + {mul_temp_90[11], {10{~mul_temp_90[11]}}})>>>11;

  assign product21 = ({{10{delay_pipeline[20][11]}}, delay_pipeline[20][11:0]} + {delay_pipeline[20][10], {9{~delay_pipeline[20][10]}}})>>>10;

  assign mul_temp_91 = delay_pipeline[19] * coeff20;
  assign product20 = (mul_temp_91[22:0] + {mul_temp_91[11], {10{~mul_temp_91[11]}}})>>>11;

  assign mul_temp_92 = delay_pipeline[18] * coeff19;
  assign product19 = (mul_temp_92[22:0] + {mul_temp_92[11], {10{~mul_temp_92[11]}}})>>>11;

  assign mulpwr2_temp_8 = (delay_pipeline[17]==12'b100000000000) ? $signed({1'b0, delay_pipeline[17]}) : -delay_pipeline[17];

  assign product18 = ({{8{mulpwr2_temp_8[12]}}, mulpwr2_temp_8[12:0]} + {mulpwr2_temp_8[9], {8{~mulpwr2_temp_8[9]}}})>>>9;

  assign product17 = ({{11{delay_pipeline[16][11]}}, delay_pipeline[16][11:0]} + {delay_pipeline[16][11], {10{~delay_pipeline[16][11]}}})>>>11;

  assign product16 = ({{9{delay_pipeline[15][11]}}, delay_pipeline[15][11:0]} + {delay_pipeline[15][9], {8{~delay_pipeline[15][9]}}})>>>9;

  assign mul_temp_93 = delay_pipeline[14] * coeff15;
  assign product15 = (mul_temp_93[22:0] + {mul_temp_93[11], {10{~mul_temp_93[11]}}})>>>11;

  assign product14 = ({{11{delay_pipeline[13][11]}}, delay_pipeline[13][11:0]} + {delay_pipeline[13][11], {10{~delay_pipeline[13][11]}}})>>>11;

  assign mulpwr2_temp_9 = (delay_pipeline[12]==12'b100000000000) ? $signed({1'b0, delay_pipeline[12]}) : -delay_pipeline[12];

  assign product13 = ({{10{mulpwr2_temp_9[12]}}, mulpwr2_temp_9[12:0]} + {mulpwr2_temp_9[11], {10{~mulpwr2_temp_9[11]}}})>>>11;

  assign mulpwr2_temp_10 = (delay_pipeline[11]==12'b100000000000) ? $signed({1'b0, delay_pipeline[11]}) : -delay_pipeline[11];

  assign product12 = ({{9{mulpwr2_temp_10[12]}}, mulpwr2_temp_10[12:0]} + {mulpwr2_temp_10[10], {9{~mulpwr2_temp_10[10]}}})>>>10;

  assign mulpwr2_temp_11 = (delay_pipeline[10]==12'b100000000000) ? $signed({1'b0, delay_pipeline[10]}) : -delay_pipeline[10];

  assign product11 = ({{10{mulpwr2_temp_11[12]}}, mulpwr2_temp_11[12:0]} + {mulpwr2_temp_11[11], {10{~mulpwr2_temp_11[11]}}})>>>11;

  assign mul_temp_94 = delay_pipeline[4] * coeff5;
  assign product5 = (mul_temp_94[22:0] + {mul_temp_94[11], {10{~mul_temp_94[11]}}})>>>11;

  assign mul_temp_95 = delay_pipeline[3] * coeff4;
  assign product4 = (mul_temp_95[22:0] + {mul_temp_95[11], {10{~mul_temp_95[11]}}})>>>11;

  assign mul_temp_96 = delay_pipeline[2] * coeff3;
  assign product3 = (mul_temp_96[22:0] + {mul_temp_96[11], {10{~mul_temp_96[11]}}})>>>11;

  assign mul_temp_97 = delay_pipeline[1] * coeff2;
  assign product2 = (mul_temp_97[22:0] + {mul_temp_97[11], {10{~mul_temp_97[11]}}})>>>11;

  assign product1_cast = product1;

  assign mul_temp_98 = delay_pipeline[0] * coeff1;
  assign product1 = (mul_temp_98[22:0] + {mul_temp_98[11], {10{~mul_temp_98[11]}}})>>>11;

  assign add_signext = product1_cast;
  assign add_signext_1 = product2;
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[11:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = product3;
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[11:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = product4;
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[11:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = product5;
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[11:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = product11;
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[11:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = product12;
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[11:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = product13;
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[11:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = product14;
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[11:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = product15;
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[11:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = product16;
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[11:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = product17;
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = add_temp_10[11:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = product18;
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = add_temp_11[11:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = product19;
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = add_temp_12[11:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = product20;
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = add_temp_13[11:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = product21;
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = add_temp_14[11:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = product22;
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = add_temp_15[11:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = product23;
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = add_temp_16[11:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = product24;
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = add_temp_17[11:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = product25;
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = add_temp_18[11:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = product26;
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = add_temp_19[11:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = product27;
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = add_temp_20[11:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = product28;
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = add_temp_21[11:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = product29;
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = add_temp_22[11:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = product30;
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = add_temp_23[11:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = product31;
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = add_temp_24[11:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = product32;
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = add_temp_25[11:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = product33;
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = add_temp_26[11:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = product34;
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = add_temp_27[11:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = product35;
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = add_temp_28[11:0];

  assign add_signext_58 = sum29;
  assign add_signext_59 = product36;
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum30 = add_temp_29[11:0];

  assign add_signext_60 = sum30;
  assign add_signext_61 = product37;
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum31 = add_temp_30[11:0];

  assign add_signext_62 = sum31;
  assign add_signext_63 = product38;
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum32 = add_temp_31[11:0];

  assign add_signext_64 = sum32;
  assign add_signext_65 = product39;
  assign add_temp_32 = add_signext_64 + add_signext_65;
  assign sum33 = add_temp_32[11:0];

  assign add_signext_66 = sum33;
  assign add_signext_67 = product40;
  assign add_temp_33 = add_signext_66 + add_signext_67;
  assign sum34 = add_temp_33[11:0];

  assign add_signext_68 = sum34;
  assign add_signext_69 = product41;
  assign add_temp_34 = add_signext_68 + add_signext_69;
  assign sum35 = add_temp_34[11:0];

  assign add_signext_70 = sum35;
  assign add_signext_71 = product42;
  assign add_temp_35 = add_signext_70 + add_signext_71;
  assign sum36 = add_temp_35[11:0];

  assign add_signext_72 = sum36;
  assign add_signext_73 = product43;
  assign add_temp_36 = add_signext_72 + add_signext_73;
  assign sum37 = add_temp_36[11:0];

  assign add_signext_74 = sum37;
  assign add_signext_75 = product44;
  assign add_temp_37 = add_signext_74 + add_signext_75;
  assign sum38 = add_temp_37[11:0];

  assign add_signext_76 = sum38;
  assign add_signext_77 = product45;
  assign add_temp_38 = add_signext_76 + add_signext_77;
  assign sum39 = add_temp_38[11:0];

  assign add_signext_78 = sum39;
  assign add_signext_79 = product46;
  assign add_temp_39 = add_signext_78 + add_signext_79;
  assign sum40 = add_temp_39[11:0];

  assign add_signext_80 = sum40;
  assign add_signext_81 = product47;
  assign add_temp_40 = add_signext_80 + add_signext_81;
  assign sum41 = add_temp_40[11:0];

  assign add_signext_82 = sum41;
  assign add_signext_83 = product48;
  assign add_temp_41 = add_signext_82 + add_signext_83;
  assign sum42 = add_temp_41[11:0];

  assign add_signext_84 = sum42;
  assign add_signext_85 = product49;
  assign add_temp_42 = add_signext_84 + add_signext_85;
  assign sum43 = add_temp_42[11:0];

  assign add_signext_86 = sum43;
  assign add_signext_87 = product50;
  assign add_temp_43 = add_signext_86 + add_signext_87;
  assign sum44 = add_temp_43[11:0];

  assign add_signext_88 = sum44;
  assign add_signext_89 = product51;
  assign add_temp_44 = add_signext_88 + add_signext_89;
  assign sum45 = add_temp_44[11:0];

  assign add_signext_90 = sum45;
  assign add_signext_91 = product52;
  assign add_temp_45 = add_signext_90 + add_signext_91;
  assign sum46 = add_temp_45[11:0];

  assign add_signext_92 = sum46;
  assign add_signext_93 = product53;
  assign add_temp_46 = add_signext_92 + add_signext_93;
  assign sum47 = add_temp_46[11:0];

  assign add_signext_94 = sum47;
  assign add_signext_95 = product54;
  assign add_temp_47 = add_signext_94 + add_signext_95;
  assign sum48 = add_temp_47[11:0];

  assign add_signext_96 = sum48;
  assign add_signext_97 = product55;
  assign add_temp_48 = add_signext_96 + add_signext_97;
  assign sum49 = add_temp_48[11:0];

  assign add_signext_98 = sum49;
  assign add_signext_99 = product56;
  assign add_temp_49 = add_signext_98 + add_signext_99;
  assign sum50 = add_temp_49[11:0];

  assign add_signext_100 = sum50;
  assign add_signext_101 = product57;
  assign add_temp_50 = add_signext_100 + add_signext_101;
  assign sum51 = add_temp_50[11:0];

  assign add_signext_102 = sum51;
  assign add_signext_103 = product58;
  assign add_temp_51 = add_signext_102 + add_signext_103;
  assign sum52 = add_temp_51[11:0];

  assign add_signext_104 = sum52;
  assign add_signext_105 = product59;
  assign add_temp_52 = add_signext_104 + add_signext_105;
  assign sum53 = add_temp_52[11:0];

  assign add_signext_106 = sum53;
  assign add_signext_107 = product60;
  assign add_temp_53 = add_signext_106 + add_signext_107;
  assign sum54 = add_temp_53[11:0];

  assign add_signext_108 = sum54;
  assign add_signext_109 = product61;
  assign add_temp_54 = add_signext_108 + add_signext_109;
  assign sum55 = add_temp_54[11:0];

  assign add_signext_110 = sum55;
  assign add_signext_111 = product62;
  assign add_temp_55 = add_signext_110 + add_signext_111;
  assign sum56 = add_temp_55[11:0];

  assign add_signext_112 = sum56;
  assign add_signext_113 = product63;
  assign add_temp_56 = add_signext_112 + add_signext_113;
  assign sum57 = add_temp_56[11:0];

  assign add_signext_114 = sum57;
  assign add_signext_115 = product64;
  assign add_temp_57 = add_signext_114 + add_signext_115;
  assign sum58 = add_temp_57[11:0];

  assign add_signext_116 = sum58;
  assign add_signext_117 = product65;
  assign add_temp_58 = add_signext_116 + add_signext_117;
  assign sum59 = add_temp_58[11:0];

  assign add_signext_118 = sum59;
  assign add_signext_119 = product66;
  assign add_temp_59 = add_signext_118 + add_signext_119;
  assign sum60 = add_temp_59[11:0];

  assign add_signext_120 = sum60;
  assign add_signext_121 = product67;
  assign add_temp_60 = add_signext_120 + add_signext_121;
  assign sum61 = add_temp_60[11:0];

  assign add_signext_122 = sum61;
  assign add_signext_123 = product68;
  assign add_temp_61 = add_signext_122 + add_signext_123;
  assign sum62 = add_temp_61[11:0];

  assign add_signext_124 = sum62;
  assign add_signext_125 = product69;
  assign add_temp_62 = add_signext_124 + add_signext_125;
  assign sum63 = add_temp_62[11:0];

  assign add_signext_126 = sum63;
  assign add_signext_127 = product70;
  assign add_temp_63 = add_signext_126 + add_signext_127;
  assign sum64 = add_temp_63[11:0];

  assign add_signext_128 = sum64;
  assign add_signext_129 = product71;
  assign add_temp_64 = add_signext_128 + add_signext_129;
  assign sum65 = add_temp_64[11:0];

  assign add_signext_130 = sum65;
  assign add_signext_131 = product72;
  assign add_temp_65 = add_signext_130 + add_signext_131;
  assign sum66 = add_temp_65[11:0];

  assign add_signext_132 = sum66;
  assign add_signext_133 = product73;
  assign add_temp_66 = add_signext_132 + add_signext_133;
  assign sum67 = add_temp_66[11:0];

  assign add_signext_134 = sum67;
  assign add_signext_135 = product74;
  assign add_temp_67 = add_signext_134 + add_signext_135;
  assign sum68 = add_temp_67[11:0];

  assign add_signext_136 = sum68;
  assign add_signext_137 = product75;
  assign add_temp_68 = add_signext_136 + add_signext_137;
  assign sum69 = add_temp_68[11:0];

  assign add_signext_138 = sum69;
  assign add_signext_139 = product76;
  assign add_temp_69 = add_signext_138 + add_signext_139;
  assign sum70 = add_temp_69[11:0];

  assign add_signext_140 = sum70;
  assign add_signext_141 = product77;
  assign add_temp_70 = add_signext_140 + add_signext_141;
  assign sum71 = add_temp_70[11:0];

  assign add_signext_142 = sum71;
  assign add_signext_143 = product78;
  assign add_temp_71 = add_signext_142 + add_signext_143;
  assign sum72 = add_temp_71[11:0];

  assign add_signext_144 = sum72;
  assign add_signext_145 = product79;
  assign add_temp_72 = add_signext_144 + add_signext_145;
  assign sum73 = add_temp_72[11:0];

  assign add_signext_146 = sum73;
  assign add_signext_147 = product80;
  assign add_temp_73 = add_signext_146 + add_signext_147;
  assign sum74 = add_temp_73[11:0];

  assign add_signext_148 = sum74;
  assign add_signext_149 = product81;
  assign add_temp_74 = add_signext_148 + add_signext_149;
  assign sum75 = add_temp_74[11:0];

  assign add_signext_150 = sum75;
  assign add_signext_151 = product82;
  assign add_temp_75 = add_signext_150 + add_signext_151;
  assign sum76 = add_temp_75[11:0];

  assign add_signext_152 = sum76;
  assign add_signext_153 = product83;
  assign add_temp_76 = add_signext_152 + add_signext_153;
  assign sum77 = add_temp_76[11:0];

  assign add_signext_154 = sum77;
  assign add_signext_155 = product84;
  assign add_temp_77 = add_signext_154 + add_signext_155;
  assign sum78 = add_temp_77[11:0];

  assign add_signext_156 = sum78;
  assign add_signext_157 = product85;
  assign add_temp_78 = add_signext_156 + add_signext_157;
  assign sum79 = add_temp_78[11:0];

  assign add_signext_158 = sum79;
  assign add_signext_159 = product86;
  assign add_temp_79 = add_signext_158 + add_signext_159;
  assign sum80 = add_temp_79[11:0];

  assign add_signext_160 = sum80;
  assign add_signext_161 = product87;
  assign add_temp_80 = add_signext_160 + add_signext_161;
  assign sum81 = add_temp_80[11:0];

  assign add_signext_162 = sum81;
  assign add_signext_163 = product88;
  assign add_temp_81 = add_signext_162 + add_signext_163;
  assign sum82 = add_temp_81[11:0];

  assign add_signext_164 = sum82;
  assign add_signext_165 = product89;
  assign add_temp_82 = add_signext_164 + add_signext_165;
  assign sum83 = add_temp_82[11:0];

  assign add_signext_166 = sum83;
  assign add_signext_167 = product90;
  assign add_temp_83 = add_signext_166 + add_signext_167;
  assign sum84 = add_temp_83[11:0];

  assign add_signext_168 = sum84;
  assign add_signext_169 = product91;
  assign add_temp_84 = add_signext_168 + add_signext_169;
  assign sum85 = add_temp_84[11:0];

  assign add_signext_170 = sum85;
  assign add_signext_171 = product92;
  assign add_temp_85 = add_signext_170 + add_signext_171;
  assign sum86 = add_temp_85[11:0];

  assign add_signext_172 = sum86;
  assign add_signext_173 = product93;
  assign add_temp_86 = add_signext_172 + add_signext_173;
  assign sum87 = add_temp_86[11:0];

  assign add_signext_174 = sum87;
  assign add_signext_175 = product94;
  assign add_temp_87 = add_signext_174 + add_signext_175;
  assign sum88 = add_temp_87[11:0];

  assign add_signext_176 = sum88;
  assign add_signext_177 = product95;
  assign add_temp_88 = add_signext_176 + add_signext_177;
  assign sum89 = add_temp_88[11:0];

  assign add_signext_178 = sum89;
  assign add_signext_179 = product96;
  assign add_temp_89 = add_signext_178 + add_signext_179;
  assign sum90 = add_temp_89[11:0];

  assign add_signext_180 = sum90;
  assign add_signext_181 = product97;
  assign add_temp_90 = add_signext_180 + add_signext_181;
  assign sum91 = add_temp_90[11:0];

  assign add_signext_182 = sum91;
  assign add_signext_183 = product98;
  assign add_temp_91 = add_signext_182 + add_signext_183;
  assign sum92 = add_temp_91[11:0];

  assign add_signext_184 = sum92;
  assign add_signext_185 = product99;
  assign add_temp_92 = add_signext_184 + add_signext_185;
  assign sum93 = add_temp_92[11:0];

  assign add_signext_186 = sum93;
  assign add_signext_187 = product100;
  assign add_temp_93 = add_signext_186 + add_signext_187;
  assign sum94 = add_temp_93[11:0];

  assign add_signext_188 = sum94;
  assign add_signext_189 = product101;
  assign add_temp_94 = add_signext_188 + add_signext_189;
  assign sum95 = add_temp_94[11:0];

  assign add_signext_190 = sum95;
  assign add_signext_191 = product102;
  assign add_temp_95 = add_signext_190 + add_signext_191;
  assign sum96 = add_temp_95[11:0];

  assign add_signext_192 = sum96;
  assign add_signext_193 = product103;
  assign add_temp_96 = add_signext_192 + add_signext_193;
  assign sum97 = add_temp_96[11:0];

  assign add_signext_194 = sum97;
  assign add_signext_195 = product104;
  assign add_temp_97 = add_signext_194 + add_signext_195;
  assign sum98 = add_temp_97[11:0];

  assign add_signext_196 = sum98;
  assign add_signext_197 = product105;
  assign add_temp_98 = add_signext_196 + add_signext_197;
  assign sum99 = add_temp_98[11:0];

  assign add_signext_198 = sum99;
  assign add_signext_199 = product106;
  assign add_temp_99 = add_signext_198 + add_signext_199;
  assign sum100 = add_temp_99[11:0];

  assign add_signext_200 = sum100;
  assign add_signext_201 = product107;
  assign add_temp_100 = add_signext_200 + add_signext_201;
  assign sum101 = add_temp_100[11:0];

  assign add_signext_202 = sum101;
  assign add_signext_203 = product108;
  assign add_temp_101 = add_signext_202 + add_signext_203;
  assign sum102 = add_temp_101[11:0];

  assign add_signext_204 = sum102;
  assign add_signext_205 = product109;
  assign add_temp_102 = add_signext_204 + add_signext_205;
  assign sum103 = add_temp_102[11:0];

  assign add_signext_206 = sum103;
  assign add_signext_207 = product110;
  assign add_temp_103 = add_signext_206 + add_signext_207;
  assign sum104 = add_temp_103[11:0];

  assign add_signext_208 = sum104;
  assign add_signext_209 = product111;
  assign add_temp_104 = add_signext_208 + add_signext_209;
  assign sum105 = add_temp_104[11:0];

  assign add_signext_210 = sum105;
  assign add_signext_211 = product112;
  assign add_temp_105 = add_signext_210 + add_signext_211;
  assign sum106 = add_temp_105[11:0];

  assign add_signext_212 = sum106;
  assign add_signext_213 = product113;
  assign add_temp_106 = add_signext_212 + add_signext_213;
  assign sum107 = add_temp_106[11:0];

  assign add_signext_214 = sum107;
  assign add_signext_215 = product114;
  assign add_temp_107 = add_signext_214 + add_signext_215;
  assign sum108 = add_temp_107[11:0];

  assign add_signext_216 = sum108;
  assign add_signext_217 = product115;
  assign add_temp_108 = add_signext_216 + add_signext_217;
  assign sum109 = add_temp_108[11:0];

  assign add_signext_218 = sum109;
  assign add_signext_219 = product116;
  assign add_temp_109 = add_signext_218 + add_signext_219;
  assign sum110 = add_temp_109[11:0];

  assign add_signext_220 = sum110;
  assign add_signext_221 = product117;
  assign add_temp_110 = add_signext_220 + add_signext_221;
  assign sum111 = add_temp_110[11:0];

  assign add_signext_222 = sum111;
  assign add_signext_223 = product118;
  assign add_temp_111 = add_signext_222 + add_signext_223;
  assign sum112 = add_temp_111[11:0];

  assign add_signext_224 = sum112;
  assign add_signext_225 = product119;
  assign add_temp_112 = add_signext_224 + add_signext_225;
  assign sum113 = add_temp_112[11:0];

  assign add_signext_226 = sum113;
  assign add_signext_227 = product120;
  assign add_temp_113 = add_signext_226 + add_signext_227;
  assign sum114 = add_temp_113[11:0];

  assign add_signext_228 = sum114;
  assign add_signext_229 = product121;
  assign add_temp_114 = add_signext_228 + add_signext_229;
  assign sum115 = add_temp_114[11:0];

  assign add_signext_230 = sum115;
  assign add_signext_231 = product122;
  assign add_temp_115 = add_signext_230 + add_signext_231;
  assign sum116 = add_temp_115[11:0];

  assign add_signext_232 = sum116;
  assign add_signext_233 = product123;
  assign add_temp_116 = add_signext_232 + add_signext_233;
  assign sum117 = add_temp_116[11:0];

  assign add_signext_234 = sum117;
  assign add_signext_235 = product124;
  assign add_temp_117 = add_signext_234 + add_signext_235;
  assign sum118 = add_temp_117[11:0];

  assign add_signext_236 = sum118;
  assign add_signext_237 = product125;
  assign add_temp_118 = add_signext_236 + add_signext_237;
  assign sum119 = add_temp_118[11:0];

  assign add_signext_238 = sum119;
  assign add_signext_239 = product131;
  assign add_temp_119 = add_signext_238 + add_signext_239;
  assign sum120 = add_temp_119[11:0];

  assign add_signext_240 = sum120;
  assign add_signext_241 = product132;
  assign add_temp_120 = add_signext_240 + add_signext_241;
  assign sum121 = add_temp_120[11:0];

  assign add_signext_242 = sum121;
  assign add_signext_243 = product133;
  assign add_temp_121 = add_signext_242 + add_signext_243;
  assign sum122 = add_temp_121[11:0];

  assign add_signext_244 = sum122;
  assign add_signext_245 = product134;
  assign add_temp_122 = add_signext_244 + add_signext_245;
  assign sum123 = add_temp_122[11:0];

  assign add_signext_246 = sum123;
  assign add_signext_247 = product135;
  assign add_temp_123 = add_signext_246 + add_signext_247;
  assign sum124 = add_temp_123[11:0];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum124;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // Fir_filterrr
